### ISSUE TITLE
Voting: enacting/not enacted copy

### ISSUE THREAD

**Issue by AquiGorka** [aragon/aragon-apps#1002]
References:
- https://github.com/aragonone/product/issues/196
- https://www.notion.so/aragon/Design-review-0-8-items-bf12838cc3874c05811a96722a961ccd#2fcd62c74601462995ea1c9544170687

Work:
- [ ] User testing to define best wording + behaviour
- [ ] Designs
- [ ] Implementation

**Comment by sohkai** [comment]
Closing; so far the existing filter does not seem to have confused anyone.
