### ISSUE TITLE
Remove abi folder from npm package

### ISSUE THREAD

**Issue by 0xGabi** [aragon/aragon-apps#1003]
I wonder why are both the `abi` and `build` folder included in the npm distribution of the apps. Seems the `abi` folder is a bit unnecessary cause the information is already available in each artifact within the `build` folder

**Comment by sohkai** [comment]
> Seems the abi folder is a bit unnecessary cause the information is already available in each artifact within the build folder

I've taken this route to just expose the `abi` folder when frontends need this information and add it to their bundles as there's no need to include the extra information from the `build` files. Most of our apps actually use _very small_ hand-picked subsets, but this is not great UX and it's easier for people to just import an entire ABI.

**Comment by sohkai** [comment]
Going to close this for now, since this is the model we generally follow in contract packages.
