### ISSUE TITLE
Token Manager: "you" pill is partially hidden in sidebar

### ISSUE THREAD

**Issue by pythonpete32** [aragon/aragon-apps#1008]
in the ownership distribution tab, the pill indicating the current unlocked account is partially hidden behind the percentage

![uierror](https://user-images.githubusercontent.com/50079365/65308585-4583ae80-db82-11e9-9b78-2da673687f14.png)

**Comment by dizzypaty** [comment]
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/7205369/78694360-71833900-78f4-11ea-911f-4d7612c9ec0c.png">

cc @delfipolito 🙌🏻
