### ISSUE TITLE
MiniMe supply overflows silently

### ISSUE THREAD

**Issue by ajsantander** [aragon/aragon-apps#1009]
Even though this only happens with hardcore token amounts larger than max uint128 (`2 ** 128 - 1`), if the token supply exceeds this limit, it goes back to zero.

I've setup a branch to illustrate the bug: https://github.com/aragon/aragon-apps/tree/overflow-bug

To reproduce:
- Checkout the branch
- `git checkout 052104799400a99567d26eede04ced7c30322c4b`
- `npm i`
- `cd apps/token-manager`
- `npm t`

The tests are `.only`-ed here, focusing on the bug:
https://github.com/aragon/aragon-apps/blob/052104799400a99567d26eede04ced7c30322c4b/apps/token-manager/test/tokenmanager.js#L121

TokenManager could detect this and revert when exceeding the limit, but MiniMe should be updated as well.

**Comment by sohkai** [comment]
Closing; this has been fixed separately in [aragon/minime](https://github.com/aragon/minime).
