### ISSUE TITLE
Token icon provider is down

### ISSUE THREAD

**Issue by sembrestels** [aragon/aragon-apps#1011]
The service https://chasing-coins.com/ is down and it may be interfering with the Finance app, since all images need to be loaded before the app frontend appears (until image loading timeouts).

This is the affected line:

https://github.com/aragon/aragon-apps/blob/e90e917693c7c1b65772e02755b69f7dc79e01b7/apps/finance/app/src/components/BalanceToken.js#L49

**Comment by sohkai** [comment]
Closing for https://github.com/aragon/aragon/issues/1101.
