### ISSUE TITLE
Agent, Finance: best approach for long descriptions

### ISSUE THREAD

**Issue by AquiGorka** [aragon/aragon-apps#1015]
Following up to https://github.com/aragonone/product/issues/195#issuecomment-531741566

What would be the best way to render the table's contents when these are long?
There are certain limitations with the current implementation of `DataView`: it is very hard to do a text overflow without using a hardcoded max-width (no percentages can be used and the columns adjust to its content's width).

- [ ] Needs specs

**Comment by sohkai** [comment]
Closing for https://github.com/aragon/aragon/issues/1212.
