### ISSUE TITLE
Vault: replace to.transfer(x) for to.value(x).call() to reduce EIP-1884 impact

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-apps#1017]
By doing this, upgraded instances of Vault will be able to send ETH to non-fixed proxies (pre-0.8).

As the Vault doesn't have re-entrancy issues, we should be able to make this change without issue.

This will also require publishing a new major for Agent as it inherits from Vault.

**Comment by sohkai** [comment]
I agree with this, but what is the thinking around setting arbitrary limits on the gas (~3-4k) to be extra safe? Make sure to use reentrancy guards instead?

I'd also wait until at least the end of the month (targeting a ~0.8.3 release) before re-releasing those two apps.

**Comment by izqui** [comment]
> what is the thinking around setting arbitrary limits on the gas (~3-4k) to be extra safe

Arbitrary gas limits are a bit dangerous and for this I don't think there is a reason for us to be extra safe

> I'd also wait until at least the end of the month (targeting a ~0.8.3 release) before re-releasing those two apps

Fair. It doesn't need to make it before Istanbul ships IMO, but we should get it out fairly soon

**Comment by sohkai** [comment]
We've released Agent v5 without this change, and at this point, I think it's fairly clear most important organizations are using 0.8 proxies (or can easily migrate into them).
