### ISSUE TITLE
Voting: impossible to create new informative votes

### ISSUE THREAD

**Issue by DiegoCoyote** [aragon/aragon-apps#1023]
For a few days it's impossible for me to create new informative votes. I'm using the version 0.8 camino, which have been working well until few days ago. I've tried in two computers and in one smartphone, using firefox and chrome, and the outcome is always the same. I've even create a new organization in rinkeby, but it doesn't work either. 

When I click on the "New Vote" button, the screen to write the question appears, and when I've wrote the question and click on the "Create new vote" button, this screen slides to the right and nothing else happens.

The voting app works perfectly if I want, for instance, to mint tokens - what I can't do directly - and a new vote is launched and I can use the voting app as usual.

I don't know if it's something related with my devices, thus I'm requesting help. Thanks.

**Comment by sohkai** [comment]
Thanks for pointing this out here @DiegoCoyote. This is a known issue (see https://github.com/aragon/aragon/issues/1127) and will be fixed in the next release coming in the next few days.
