### ISSUE TITLE
Vault: failure to withdraw UNI-V1 tokens from vault.

### ISSUE THREAD

**Issue by joshua-mir** [aragon/aragon-apps#1028]
Withdrawal of UNI-V1 tokens from [shokunin.argonid.eth](https://mainnet.aragon.org/#/shokunin) fail with ['VAULT_TOKEN_TRANSFER_REVERTED'](https://etherscan.io/tx/0x8c421e96fb075fc165bf24511b803d7bbbb428034e46541a42015297f765aa2c) when [previously](https://etherscan.io/tx/0xd1439ae92ef9c036829672fb6c2219675b44fea5de8dbd4dc0e3e1ab509840df) (incidentally, #614 was roughly a week after this?) a different UNI-V1 token withdrawal had succeeded.

**Comment by sohkai** [comment]
@joshua-mir It's a bit hard to debug this without having the UNI-V1 token's source code (I assume this is the token: https://etherscan.io/token/0x755160062e3e09d34af0a00ff8cab8500e81e0d7)?

That being said, `'VAULT_TOKEN_TRANSFER_REVERTED'` only happens if the token itself returned a failing condition or reverted internally, so it shouldn't be an issue with the Vault.

**Comment by joshua-mir** [comment]
Here's the relevant part of the source, IIUC it should only revert on an underflow 
https://github.com/Uniswap/contracts-vyper/blob/c10c08d81d6114f694baa8bd32f555a40f6264da/contracts/uniswap_exchange.vy#L472 - uniswap tokens are non-upgradable so I'm still not sure what could have changed for the behavior to have broken.

The token you linked was the one successfully deposited and then withdrew in January - the ones that are failing are https://etherscan.io/token/0x077d52b047735976dfda76fef74d4d988ac25196 and https://etherscan.io/token/0x1aec8f11a7e78dc22477e91ed924fab46e3a88fd - they all share the same source. 

I tried a different uniswap token address and sent only 1 unit of the token to discount an underflow: it failed again in the same way and according to [the traces](https://etherscan.io/vmtrace?txhash=0x3ea2b5d814986343a2f9fd5695b555c9c2f8cf66fb7b35d21e5d43cd8c7a1bbe&type=parity), the actual token transfer (action 12, for reference) didn't revert - unless I'm misreading something.

**Comment by joshua-mir** [comment]
Here's a confirmation of my suspicion - this is an incompatibility between SafeERC-20 and Uniswap tokens: https://github.com/ethereum/solidity/issues/5902#issuecomment-458868819

**Comment by sohkai** [comment]
We don't use OpenZeppelin's SafeERC20, but our own (from aragonOS).

Looking at this further, it looks like the contract linked in https://github.com/aragon/aragon-apps/issues/1028#issuecomment-546287946 was to the "exchange template" (whose address is [`0x2157a7894439191e520825fe9399ab8655e0f708`](https://etherscan.io/address/0x2157a7894439191e520825fe9399ab8655e0f708)).

However, the failing token appears to be [`0x077d52b047735976dfda76fef74d4d988ac25196`](https://etherscan.io/address/0x077d52b047735976dfda76fef74d4d988ac25196), which seems to act as a proxy around the "exchange template", as the traces show a delegate call.

The "exchange template" contract is returning `true` properly from the trace, but I can't tell for certain how the token itself is returning without the source.

**Comment by sohkai** [comment]
Closing; it is unclear what was causing this particular issue.
