### ISSUE TITLE
Agent: magic number does not match function 

### ISSUE THREAD

**Issue by jvluso** [aragon/aragon-apps#1030]
Right now, the `isValidSignature` method has the arguments `bytes32,bytes` but the magic number returned is `bytes4(keccak256("isValidSignature(bytes,bytes)")` I don't think that EIP 1271 has finalized whether it will be `bytes,bytes` or `bytes32,bytes` yet, but I don't think it will be a mix of the two.

**Comment by izqui** [comment]
The discussion on that EIP on whether to use `bytes,bytes` or `bytes32,bytes` got quite unproductive so I just dropped from the discussion. I personally still support having `bytes,bytes` as it allows the 'wallet' to inspect the data. `bytes32,bytes` would be fine if there was another `bytes` input (or concatenate in the signature) where a witness can be passed proving that proves part of the hash preimage is a certain piece of data.

For the magic number we should absolutely use whatever everyone uses, even if we provide an extra function that is not part of the standard

**Comment by sohkai** [comment]
Closing for #720, which covers the particular magic number.
