### ISSUE TITLE
Agent: Can not send ether from vault

### ISSUE THREAD

**Issue by xuhcc** [aragon/aragon-apps#1035]
I installed Agent to an existing organization as described in https://hack.aragon.org/docs/guides-use-agent#3-install-the-agent-app, but for some reason it can not execute any action that involves transfer of ether. 

Organization: [`0xA2d522f306cC8b42E9367a43fe7dA46Aef215d08`](https://rinkeby.aragon.org/#/0xA2d522f306cC8b42E9367a43fe7dA46Aef215d08/0x549482104bba18714c62b29d3a2ab7eb98efe68b).

There are two very similar votes:

* Vote 16: only transaction data were provided, no ether to send. Agent successfully made a call to a specified address ([`call_0_1_1_1_1_1`](https://rinkeby.etherscan.io/tx/0x1b91f14d9876bebc7f39d531607bd6bd6d49a842e077ae2d09ed00d412f526f8#internal)).
* Vote 15: sending 0.0012 ETH (total 0.1 ETH in vault) with the same transaction data. Running `dao exec` results in `Cannot find transaction path for executing action` error. Aragon Client shows `The action failed to execute. You may not have the required permissions.`.

Both Agent and Voting has the `TRANSFER_ROLE` permission assigned to them.

**Comment by sohkai** [comment]
As discussed offline, this was actually due to a misunderstanding of how the Agent's `.execute()` parameters work. In this example, vote#15 was actually trying to transfer 0.12 ETH from the Agent (which has no ETH) to an EOA account, rather than having the Agent invoke a transfer on the Vault.

**Comment by xuhcc** [comment]
For a future reference:

* It is possible to send ether from Vault with Agent, but one is limited to simple transfers:

```
dao act <agent-address> <vault-address> "transfer(address,address,uint256)" 0x0000000000000000000000000000000000000000 <destination-address> <amount>
```

* To transfer ether while interacting with external contracts (e.g. exchanging on Uniswap contract), more steps are required in addition to those currently described in https://hack.aragon.org/docs/guides-use-agent#3-install-the-agent-app:
    1. Transfer ether from the Vault to the Agent address (using the Finance app).
    2. Deploy new Finance app and initialize it with Agent address:

    ```
    dao install <dao-address> finance --app-init-args <agent-address> <budgeting-period>
    ```

    3. Assign necessary permissions to new Finance app instance.

**Comment by sohkai** [comment]
Technically you don't need to install the Finance app and attach permissions; once you've transferred tokens / ETH into Agent, you will be able to interact with contracts like Uniswap.

Finance is only useful for attaching an "accounting" frontend to Agent.
