### ISSUE TITLE
Finance: add 'max amount' button to amount input in deposit/withdrawal

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-apps#1050]
In some instances, people may want to deposit/withdraw the entire balance of a certain token in Finance (eg. performing the Sai to Dai migration).

Having a 'max amount' button (as almost all exchanges do to create orders or withdraw funds) is useful not only to prevent mistakes (see image below) but also to allow to wipe the balance of a certain token down to the last decimal (which we don't show in the UI).

<img width="576" alt=" 2019-11-25 at 7 12 54 AM" src="https://user-images.githubusercontent.com/447328/69531702-11968200-0f53-11ea-9e9e-f144df61ac0a.png">

**Comment by izqui** [comment]
The Maker migration tool solves this quite well:
<img width="521" alt="Screen Shot 2020-01-07 at 11 34 57 AM" src="https://user-images.githubusercontent.com/447328/71889155-d5556480-3141-11ea-818a-b0489ea0d010.png">

cc @dizzypaty

**Comment by sohkai** [comment]
Merging with https://github.com/aragon/aragon/issues/1301.
