### ISSUE TITLE
Cannot install on latest version of node

### ISSUE THREAD

**Issue by osarrouy** [aragon/aragon-apps#1060]
Hi guys,

All the apps rely on `@aragon/os@4.2.1` which has the following dependency tree.

```
@aragon/os@4.2.1
  └─┬ truffle-hdwallet-provider@0.0.3
    └─┬ ethereumjs-wallet@0.6.3
      └─┬ scrypt.js@0.3.0
        └── scrypt@6.0.3
```

It happens that `scrypt@6.0.3` [cannot be compiled on `node@12`](https://github.com/barrysteyn/node-scrypt/issues/192). This is a known issue that won't be fixed upstream because the `scrypt` package is not maintained anymore ...

I believe `@aragon/os@4.3.0` dumps the `truffle-hdwallet-provider@0.0.3` dependency and thus the `scrypt@6.0.3` dependency so it could be great to update all apps dependency to this later version.

Happy new year! ;)

**Comment by sohkai** [comment]
> I believe @aragon/os@4.3.0 dumps the truffle-hdwallet-provider@0.0.3 dependency and thus the scrypt@6.0.3 dependency so it could be great to update all apps dependency to this later version.

Not quite yet; we need to release `@aragon/os@4.3.1` to make that happen but we should do that soon :).

We may still need that dependency in the truffle config though... but we may have fixed it in `@aragon/truffle-config-v4`.

In the mean time, can you downgrade to node 11 or 10? 😄

**Comment by sohkai** [comment]
Closing; this will be fixed soon. Generally, node12 has been a PITA due to the node-gyp breakages :(.

**Comment by lorrp1** [comment]
@sohkai  Hello, im getting: 
```

Error running install script for optional dependency: /aragon-apps/node_modules/scrypt: Command failed.

Exit code: 1
Command: node-gyp rebuild
```

i get yarn install v1.22.10 after doing yarn in the dir
