### ISSUE TITLE
Tests: fix tests after istanbul hardfork

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon-apps#1067]
It appears quite a few of our contract tests are now failing due to the Istanbul hardfork, most likely due to gas amounts when transferring ETH.

**Comment by sohkai** [comment]
Just realized we can most likely fix this in one go by updating the aragonOS dependency.

**Comment by bingen** [comment]
I'm afraid we have a problem with Finance fallback:
https://github.com/aragon/aragon-apps/blob/buidler-migration/buidler-apps/finance/contracts/Finance.sol#L154
@ajsantander realized while testing with buidler that this test is not passing even with @aragon/os 4.3.0:
https://github.com/aragon/aragon-apps/blob/buidler-migration/buidler-apps/finance/test/finance.js#L997
Should we try to optimize that one too, like we did [with Proxy one](https://github.com/aragon/aragonOS/pull/551)?

**Comment by bingen** [comment]
I'm afraid we have a problem with Finance fallback:
https://github.com/aragon/aragon-apps/blob/buidler-migration/buidler-apps/finance/contracts/Finance.sol#L154
@ajsantander realized while testing with buidler that this test is not passing even with @aragon/os 4.3.0:
https://github.com/aragon/aragon-apps/blob/buidler-migration/buidler-apps/finance/test/finance.js#L997
Should we try to optimize that one too, like we did [with Proxy one](https://github.com/aragon/aragonOS/pull/551)?

**Comment by ajsantander** [comment]
I can confirm that Finance's "can recover ETH using AragonApp#transferToVault" test fails with a clean clone.

**Comment by bingen** [comment]
> Should we try to optimize that one too, like we did with Proxy one?

I see that fallback is already spending way more, so I don't think it's worth it.

**Comment by sohkai** [comment]
> I see that fallback is already spending way more, so I don't think it's worth it.

This fallback was not particularly intended to be used with a `send()` or `transfer()` from a contract (as it does a number of calls and logs); contracts should be using `deposit()` instead.

**Comment by sohkai** [comment]
Closing for https://github.com/aragon/aragon-apps/issues/1111—we will investigate and fix issues there.
