### ISSUE TITLE
Finance: escape CSV data + build CSV on download

### ISSUE THREAD

**Issue by bpierre** [aragon/aragon-apps#1087]
See https://github.com/aragon/aragon-apps/pull/1082/commits/c8ac5695f86b0dc2db7659693d2ddeeb177e14f7 and https://github.com/aragon/aragon-apps/pull/1082/commits/813d22f8b5fe85c62fc35bdc2edb7d069670b363 from the Agent app implementation.

**Comment by Evalir** [comment]
Done in #1103 .
