### ISSUE TITLE
Change "casted" to "cast" through this repo

### ISSUE THREAD

**Issue by john-light** [aragon/aragon-apps#1118]
The past tense of "cast" as in "cast a vote" is "cast", not "casted". The phrase "casted" still appears multiple times throughout this repo.

e.g.

```
uint256 optionsCastedLength;
```

**Comment by sohkai** [comment]
Closing and placing in https://github.com/aragon/aragon-apps/issues/1101.

All the frontends have been fixed—the only remaining places where this is still the case is in contracts, and those are usually not presented to the user :).
