### ISSUE TITLE
Voting app doesn't display correct number of tokens

### ISSUE THREAD

**Issue by cygnusv** [aragon/aragon-apps#1135]
![image](https://user-images.githubusercontent.com/2564234/80160036-de712100-85cc-11ea-869a-8df9ed677714.png)

I'm testing the use of a `VotingAggregator` as the input to the Voting app. For some reason the token amount displayed is 0. From the final percentage of minimum approval I deduce that the amount is correctly computed in the Voting app (this account has 300 tokens out of a total supply of 800), so it seems to be a UI issue, or perhaps some problem retrieving data from the `VotingAggregator`.

**Comment by sohkai** [comment]
Sorry for taking so long to respond to this, @cygnusv!

It would be helpful to know which organization you were using and saw this. We've used the Voting Aggregator before and am pretty sure it reported correct balances, but having an easy way to reproduce this will be really helpful!

**Comment by cygnusv** [comment]
Sure, here's a link to that vote:

https://rinkeby.aragon.org/#/0x41bBe5A0266e180431C6AaD5ADabb49EA70AAC12/0x4d11f52a36af647448bcb61767ee64f3d296d1a1/vote/0/

**Comment by cygnusv** [comment]
I think it may have something to do with the way I configured the Voting and VotingAggregator apps in that DAO. I installed 2 voting apps (since we wanted 2 different voting procedures), both of them connected to the same VotingAggregator, which in turn was connected to a staking contract following ERC900. The votings using the first voting app are fine, but not the ones with the second voting app (which show 0 tokens). I suspect the problem is related to the architecture I mention above. In a different DAO, I configured again 2 voting apps, but used 2 separate voting aggregators and I don't have these problems.

**Comment by sohkai** [comment]
@cygnusv Took a look at this and it's a pretty innocent bug 😄.

Your Voting Aggregator instance has declared a decimals of `18`, but your account only holds `300` ("wei") of that token, so we display it as 0. Unfortunately we can't change the decimals easily after the fact, but it sounds like you most likely wanted a decimals value of `0` instead.

**Comment by cygnusv** [comment]
Thanks for investigating!
