### ISSUE TITLE
Agent: Add support for ERC-1155 tokens

### ISSUE THREAD

**Issue by john-light** [aragon/aragon-apps#1142]
Currently the Agent app supports some ERC-1155 hybrid tokens (e.g. ERC-721/ERC-1155 hybrid) but does not support pure ERC-1155 tokens.

https://eips.ethereum.org/EIPS/eip-1155

**Comment by sohkai** [comment]
Closing to include this in the contract wishlist: https://github.com/aragon/aragon-apps/issues/1101.

Since this is going to be an endless cat and mouse game for the Agent, we will likely design a more dynamic mechanism so we don't have to keep hardcoding these interfaces.
