### ISSUE TITLE
Token symbol is not used in DemocracyTemplate

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-apps#116]

**Comment by bingen** [comment]
What do you mean exactly?
I changed that here:
https://github.com/aragon/aragon-apps/pull/112/commits/babd22b0e9c34de9dcc4be9fcb1e76e9609fc05d

**Comment by izqui** [comment]
I was unaware :) Closed by babd22b

**Comment by stellarmagnet** [comment]
whenever i create a token using democracy template, i do not get the symbol when checking on etherscan

![image](https://user-images.githubusercontent.com/2584493/38339719-9a71d4ba-3824-11e8-96f5-cbb6724f56d4.png)

![image](https://user-images.githubusercontent.com/2584493/38339730-ac9731bc-3824-11e8-9aa3-cfed34abe3ee.png)

**Comment by onbjerg** [comment]
@stellarmagnet That's because Rinkeby etherscan is super bad. It doesn't show contracts that well either

**Comment by bpierre** [comment]
We also need to update the aragon.js template module, I opened an issue https://github.com/aragon/aragon.js/issues/102
