### ISSUE TITLE
Voting: update date format

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon-apps#1161]
We should migrate all date formats to ISO-8601 (`yyyy-mm-dd`).

**Comment by ECWireless** [comment]
Anyone else working on this? If not, I can try to fix it... As far as I can tell, the only date formatting occurs in the [VoteDetail](https://github.com/aragon/aragon-apps/blob/af250ffb3fe63cb26f8e95ba2f9eb841b397c263/apps/voting/app/src/screens/VoteDetail.js#L328) component. I'll get started on this now, but in the meantime @sohkai did you spot date formatting in any other component?

**Comment by sohkai** [comment]
Done with #1165.
