### ISSUE TITLE
Agent: update help text suggesting Frame

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon-apps#1162]
We should link to https://help.aragon.org/article/37-agent and also mention that you can use Frame through `aragonCLI` and the in-app console.

**Comment by ECWireless** [comment]
@sohkai is the idea here to completely switch out the "Install Frame" link with the Agent help link? Or would simply using a Help component at the end of the original text do the trick?

<img width="468" alt="Help Component" src="https://user-images.githubusercontent.com/40322776/84680472-02c3ec80-aef0-11ea-8d33-60d7e006da22.png">

**Comment by sohkai** [comment]
I think we want to update the copy (assuming it still fits and looks nicely), to:

> The Agent app can be used to interact with external contracts.
> Learn more (link to help)

We should also update the logo to the Agent's icon :).
