### ISSUE TITLE
Agreement newAction payments

### ISSUE THREAD

**Issue by bingen** [aragon/aragon-apps#1186]
With the [last implementation](https://github.com/aragon/aragon-apps/pull/1176) of Agreement app, on new action creation the transaction fees oracle is called to fetch the token and the amount to be paid and then the transfer (token or ETH) is performed:

https://github.com/aragon/aragon-apps/blob/agreements_transaction_fees_integration/apps/agreement/contracts/Agreement.sol#L742

If we want the fees to be proportionally distributed to jurors and the governor share to be paid, the beneficiary should be the `CourtSubscriptions` module of Aragon Court, but for proper accounting [`payFees`](https://github.com/aragon/aragon-court/blob/master/contracts/subscriptions/CourtSubscriptions.sol#L145) should be used in that contract, instead of the regular token (or ETH) transfer. This has some problems:

1- It creates a strong and maybe unnecessary dependency between `Agreement` and `CourtSubscriptions`. The new model for transaction fees on new actions was meant to be different and independent of previous model of subscriptions. At the very least `Agreement` should have the definition of an interface for the beneficiary that includes that `payFees` signature.
2- The function `payFees` on `CourtSubscriptions` also fetches the information of the token and amount. That sounds redundant.

Some possible solutions:

- While we could keep the interfaces separate, in our implementation we could have `CourtSubscriptions` implement the `ITransactionFeesOracle` interface. That would somehow mitigate [2].
- For [1], we could create a small contract wrapper to be the beneficiary and to re-route funds to `CourtSubscriptions`. The problem is that it would involve another “manual” step if the token is neither ETH nor ERC223/ERC777 token with a fallback mechanism, plus the approval overhead.
- Kind of a mix of the two above, the oracle could always be the beneficiary, with a defined endpoint to be called for the payment, and then we could have our implementation to re-direct the funds to `CourtSubscriptions`, but “outside” the interface definition.
- We could try to leverage ERC165 to check if the beneficiary returned by the transaction fees oracle implements `payFees`, and in case not, do the regular transfer. This would soften the dependency explained in [1].

**Comment by facuspagnuolo** [comment]
I think there is no other way than depending on a separate interface for this: we do need the Agreement app to be able to pay these fees. I like the idea of merging the `TransactionFeesOracle` in the `CourtSubscription` module. I think we should add a third payment entry point (similar to `payFees` and `donate`) for these fees.
