### ISSUE TITLE
App frontends: add start_url to manifest.json

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon-apps#119]
See [spec](https://developer.mozilla.org/en-US/docs/Web/Manifest#start_url).

It says relative url to the site origin, which I'm just going to say is whatever IPFS / apm-serve address we get. We'll probably just use `/dist/index.html` or similar (default for `create-react-app`).

**Comment by onbjerg** [comment]
So the idea is that we load from `start_url` instead of assumin `/index.html`?

**Comment by sohkai** [comment]
Yup. This allows you to use any build structure you'd like.

**Comment by onbjerg** [comment]
Very nice

**Comment by izqui** [comment]
Closing as this happened already in all apps with frontend!
