### ISSUE TITLE
Signing "approve" transaction fails in a Dandelion org using Frame

### ISSUE THREAD

**Issue by john-light** [aragon/aragon-apps#1197]
Edit: we figured out that the original issue was caused by a bug identified in this comment:

https://github.com/aragon/aragon-apps/issues/1197#issuecomment-658470564

which appears to be a [Frame issue](https://github.com/aragon/aragon-apps/issues/1197#issuecomment-665700862) rather than an Aragon issue.

**Comment by sohkai** [comment]
Oh interesting, I wonder why we mention two transactions.

cc @fabriziovigevani is this due to an IForwarderFee interface?

**Comment by fabriziovigevani** [comment]
>  is this due to an IForwarderFee interface? 

Yes the time lock inherits from `IForwarderFee` interface.

@john-light Is it possible that you had previously pre-approved the contract for the amount of tokens? 

Re point 1, i'll look into it. What is the buffer setting you used for Dandelion Voting? I'm thinking that possibly the vote wasn't open yet ? Did you have the same behavior with vote # 1?

**Comment by john-light** [comment]
@fabriziovigevani 

> Re point 1, i'll look into it. What is the buffer setting you used for Dandelion Voting?

I don't remember what the buffer setting is and don't see a way I can find that in the frontend.

> Is it possible that you had previously pre-approved the contract for the amount of tokens?

I just tried re-creating this transaction and the first transaction showed up with an error (screenshot below) and would not allow me to proceed. After I tried doing the withdrawal again, then it only took one transaction. It seems like the transaction that errors is the `Approve` transaction and it is actually successful, despite the error message?

![dandy-error1](https://user-images.githubusercontent.com/9424721/87487760-89add700-c60c-11ea-9826-e719a563c8cf.png)

Error transaction: https://rinkeby.etherscan.io/tx/0x26aa33f5191cdbfa8c84515c5277ae38ad1a0b4914e9bdd5941eef153f9558af

Transaction that successfully creates the vote: https://rinkeby.etherscan.io/tx/0xe7918dbaa1bdf41f1925a6f371ae7f4d48117d8ff71aabeeecc1e126c3de653e

**Comment by fabriziovigevani** [comment]
Hey, sorry for the delayed response.

So since the `TimeLock` is the one forwarding the action, it won't be possible to vote on the same tx since the `msg.sender` when creating the vote would be the `TimeLock`.

> I just tried re-creating this transaction and the first transaction showed up with an error (screenshot below) and would not allow me to proceed. After I tried doing the withdrawal again, then it only took one transaction. It seems like the transaction that errors is the Approve transaction and it is actually successful, despite the error message?

hmm, the failed tx seems to be the one forwarding the action, not the `approve` one.
In this case, did it also showed the `Two transactions required` message?

**Comment by john-light** [comment]
> So since the TimeLock is the one forwarding the action, it won't be possible to vote on the same tx since the msg.sender when creating the vote would be the TimeLock.

Ok thanks for looking into this.

> hmm, the failed tx seems to be the one forwarding the action, not the approve one.
> In this case, did it also showed the Two transactions required message?

Yes, you can try yourself with Frame and see.

**Comment by fabriziovigevani** [comment]
Ah yes the tx is the `approve` but that one succeeded right? The second tx doesn't look like being submitted at all actually.

I'm definitely having the same issue with frame. I think the problem here is that since the approve is not mined yet, frame doesn't allow submitting the second tx. Metamask for example gives the error that the tx might fail but it still lets you submit it.

Not sure if there's something we could do in this case :(

**Comment by john-light** [comment]
> Ah yes the tx is the approve but that one succeeded right? The second tx doesn't look like being submitted at all actually.

Right, as I mentioned in a previous comment:

> I just tried re-creating this transaction and the first transaction showed up with an error (screenshot below) and would not allow me to proceed. After I tried doing the withdrawal again, then it only took one transaction. It seems like the transaction that errors is the Approve transaction and it is actually successful, despite the error message?

So I sign the first `approve` transaction -- it errors, and doesn't let me proceed to the second tx. However in the background we have discovered it actually is being sent and confirmed. So I try the withdrawal again, then I don't have to sign the `approve` tx again, it goes straight to the second withdrawal tx, and it goes through as expected.

> I'm definitely having the same issue with frame. I think the problem here is that since the approve is not mined yet, frame doesn't allow submitting the second tx.

Ah in that case yeah it might be a Frame issue, not an Aragon problem.

**Comment by sohkai** [comment]
> If the new tx step modal is implemented in the client i think this issue should be solved since the second tx would only be submitted after the approve is confirmed correct

For the moment, we are not waiting for the transactions to be mined in the new stepper (that may be a later improvement).

**Comment by john-light** [comment]
Closing since the original issue is determined to be a Frame issue, not an Aragon issue.
