### ISSUE TITLE
Move `assertAmountOfRawEvents` to contract helpers repo

### ISSUE THREAD

**Issue by bingen** [aragon/aragon-apps#1211]
And remove it from `apps/agreement/test/helpers/assert/assertEvent.js`.
See [this comment](https://github.com/aragon/aragon-apps/pull/1199#discussion_r454491098) for reference.

**Comment by sohkai** [comment]
Funny, I was thinking about if this would be useful last night and it looks like it is!

It's a breaking API change, but I think the best way is to do this transparently in our event utilities: https://github.com/aragon/aragon-apps/issues/1211.

**Comment by bingen** [comment]
> Funny, I was thinking about if this would be useful last night and it looks like it is!
> 
> It's a breaking API change, but I think the best way is to do this transparently in our event utilities: #1211.

Even funnier the self reference! ;-)

**Comment by sohkai** [comment]
Closing for https://github.com/aragon/contract-helpers/pull/45 :)
