### ISSUE TITLE
remove app folder in each aragon-app

### ISSUE THREAD

**Issue by gasolin** [aragon/aragon-apps#124]
Since correspondent frontend are located in `aragon-app`, `app/` folders in each aragon-app are not helpful and confuse the code reader. I suggest to remove app folder from aragon-apps

**Comment by sohkai** [comment]
Hey @gasolin—this probably looks confusing right now because we haven't merged any of the frontends into the master branch yet.

The way it should look is `aragon-apps/apps/<app name>/app/<front-end>`, where `aragon-apps/apps/<app name>/contracts/<contracts>` are the contracts. Does that make more sense?

Or is it the naming of "app" (better as "frontend") that's confusing?

**Comment by gasolin** [comment]
If I understand correctly, `aragon-apps`(main branch?) is focused on contracts and `aragon` is focued on dapp (frontend). As you said the release version will based on `aragon-apps` and merge the frontend part into `aragon-apps/apps/<app name>/app/<front-end>`. (Though I haven't find correspondent front-end in `aragon` repo, @sohkai could you point me the right place?)

That looks like a common approach to organize contract & dapp. It's fine if you will update dapp into these folders or think its easier to merge code with the placeholder. 

If the merge won't happen soon, it will be nice if you can add some hints in readme or in `index.html` like.

```
<h1>Fundraising</h1>
<p>a place holder to be overwrite with aragon/aragon-<dapp>/app/</p>
```

To not confuse the code reader

**Comment by sohkai** [comment]
`aragon/aragon-apps` will have the contracts and front-end apps for all the apps. `aragon/aragon` will be the dapp "wrapper" running these apps.

The merge will be happening very soon! For example, you can see how the [voting app's frontend currently looks](https://github.com/aragon/aragon-apps/tree/master/apps/voting/app).

**Comment by gasolin** [comment]
Sounds good to me. Looking forward the merge.
