### ISSUE TITLE
Add native ether support in Vault and remove all references to EtherToken

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-apps#125]
Original conversation: https://github.com/aragon/aragonOS/issues/245

**Comment by izqui** [comment]
I will be working on this today and try to squeeze it into the release :)

**Comment by bingen** [comment]
Ya, that dynamic vault is really nice!!

**Comment by gasolin** [comment]
Wow! dynamic vault looks cool and definitely like to have it:+1: 
Though just in case I saw the rest of works for [0.5 milestone](https://github.com/aragon/aragon-apps/milestone/2) are around test and increasing the test coverage. Introducing a new feature at last time (I saw in `aragon.chat` the release might happen in this week?) increase the risk to deliver the shortern goal. And I think dynamic vault deserves a better UI companion to handle new token types like NFT #44.

**Comment by izqui** [comment]
The release is testnet only, and this changes are going to make it into the release without problem. Auditors are going to be reviewing this leading to mainnet launch. 

Actually interesting thought about NFTs, it is maybe not a crazy thought that we can do a NFT connector rather than another Vault. We won't be working on this right away but interesting.
