### ISSUE TITLE
Implement NFT (ERC721) Token Manager

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-apps#130]

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xa867a9ab4d263e754952cd1781e63e776f52dcd07b1b01896e6334a0c1bb4a05](https://etherscan.io/tx/0xa867a9ab4d263e754952cd1781e63e776f52dcd07b1b01896e6334a0c1bb4a05)

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xc9ac11c3917692c818a439816ffac4e2a6c85d57671ddd452333424ca5482f07](https://etherscan.io/tx/0xc9ac11c3917692c818a439816ffac4e2a6c85d57671ddd452333424ca5482f07)

**Comment by osarrouy** [comment]
Hey guys,

I'm currently working on the smart contracts which will run the Chaos Machine DAO - basically a crypto-jukebox which grants you a slot in a playlist by burning bank bills ...

I'm think of using ERC721 to do so.

What would need to run a Token Manager able to handle ERC721 ? The same function as the MiniMe Token manager ?

**Comment by izqui** [comment]
Yes that's the idea. An NFT token manager would be allowed to mint new tokens if allowed by the ACL.

**Comment by izqui** [comment]
Already implemented by DAppNode's @eduadiez: https://github.com/eduadiez/DAppNodeNFT
