### ISSUE TITLE
Make app's frontends lerna packages

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-apps#158]

**Comment by sohkai** [comment]
You mean we're going to have lerna packages inside lerna packages? Oh boy.

**Comment by onbjerg** [comment]
@sohkai No I think he wants a separate directory for front-ends so we can just do `lerna bootstrap`

**Comment by sohkai** [comment]
@izqui I think the idea around this doesn't align well with how our CLI currently expects a project to be structured.

One thing we can do to install the frontends on `bootstrap` is to add a `install` hook to also install the frontend's dependencies.

**Comment by sohkai** [comment]
Fixed by https://github.com/aragon/aragon-apps/pull/382.
