### ISSUE TITLE
Multisig app

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-apps#17]
At the present moment the most widely used governance mechanism is through a multisig. 

Different alternatives for implementation:
- Use a widely used trusted multisig like Gnosis.
- Extend Group app to require `n` confirmations before performing action (currently Group app is a 1 out of `m` multisig)

I personally think it is a better idea to implement our own solution for this on top of the Group app. Another question if we go down this route is whether we have two separate apps (Group and Multisig) or the current Group functionality is just a Multisig with only one required signature.

**Comment by onbjerg** [comment]
I think adding confirmations to the group app is an exciting prospect as it has different use cases. Also, a group app with multiple confirmations + the vault is pretty much a multisig.
