### ISSUE TITLE
Voting app events

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-apps#18]
~**Done** We should add an event to log when the `changeMinAcceptQuorumPct` happens.~

Also we should the number of votes that got casted in the `CastVote` event

**Comment by onbjerg** [comment]
I don't think #2 is strictly necessary, since the # of cast votes can be inferred from the # of events for any particular vote ID.

**Comment by adamdossa** [comment]
Currently the event signature is:
`event CastVote(uint256 indexed voteId, address indexed voter, bool supports);`

The suggestion was to add a parameter to capture the number of votes being cast (i.e. the token balance associated with the vote being cast). Not all votes are equal as different entities will have different balances.

**Comment by onbjerg** [comment]
Ah, that makes sense.

**Comment by onbjerg** [comment]
@izqui Want to open a new issue with just that or should we reopen this one?

**Comment by izqui** [comment]
Let's just reopen this one
