### ISSUE TITLE
Implement ERC900 connector in Vault

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-apps#184]
Having a certain stake in a Staking app is almost the same as owning an asset directly, given the risks and conditions you are bound to by staking. Thanks to our new multi-standard vault app we can handle staked tokens using the same API as if they were assets in the Vault 😎

Given that ERC900 contracts are defined as uni-token we can do:
```solidity
StakingConnector(vault).transfer(stakingApp, to, amount)
```

It allows us not to break the current Vault API, with the exception that the first address is not a token, but another type of asset the Vault owns, in this case a stake. From a smart contract point of view, they behave very similarly to tokens anyway.

Rough prototype (non-compiling) of the connector:
```solidity
contract ERC900Connector {
    function deposit(address stakingApp, address who, uint256 value, bytes how) payable external returns (bool) {
       Vault(this).transfer(stakingApp.token(), this, value, how);
       // create allowance
       stakingApp.stake(value, how)
    }

    function transfer(address stakingApp, address to, uint256 value, bytes how)   {
        stakingApp.unstake(value, how);
        Vault(this).transfer(stakingApp.token(), to, value, how);
        return true;
    }

    function balance(address stakingApp) public view returns (uint256) {
        return stakingApp.totalStakedFor(this);
    }
}
```

The above code uses the vault recursively for doing the actual transferring of tokens, it would require the vault to have permission to transfer its own tokens, which makes it a bit more dangerous security wise given a bad connector (that would be being in a pretty fucked up place in any case), but it feels like the way to go.

**This would allow organizations to manage their stakes in the Aragon Network directly from the Vault**💥

**Comment by sohkai** [comment]
Closing, as we've replaced the old vault (#292). We can re-open when the time comes to upgrade to the new vault.
