### ISSUE TITLE
Add initialization checks to critical functions in apps

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-apps#188]

**Comment by bingen** [comment]
It's already impossible as it fails trying to call some `token` functions. I can also add an explicit check if you want me to.

**Comment by izqui** [comment]
I think adding a explicit failure on creation wouldn't be a bad idea

**Comment by sohkai** [comment]
We could also add the required init modifiers to other apps, e.g. finance not allowing payments to be created until it's been initialized.
