### ISSUE TITLE
Update aragon-core dependency to 1.0.2 and adapt tests to Byzantium

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-apps#21]
A similar PR was already merged for aragon-core which could be used for reference: https://github.com/aragon/aragon-core/pull/145

**Comment by yippee-ki-yay** [comment]
Hi this seems like a good first issue I can actually do, is it ok if I work on this?

**Comment by onbjerg** [comment]
Sure! Go ahead @yippee-ki-yay 😊
