### ISSUE TITLE
Show token holder voting power on a given vote

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-apps#212]
Because each vote has a different `snapshotBlock` for checking token balances, a holder may have different voting power on proposals depending on when the vote was created.

We should communicate both the `snapshotBlock` and the voting power per proposal. This can be fetched: `token.balanceOfAt(holder, vote.snapshotBlock)`

**Comment by sohkai** [comment]
The balance of has been fixed at https://github.com/aragon/aragon-apps/pull/342.

We don't display the `snapshotBlock` yet, though.

**Comment by jounih** [comment]
<img width="1387" alt="screen shot 2018-09-05 at 18 11 21" src="https://user-images.githubusercontent.com/10109867/45109669-1d244000-b138-11e8-9134-753317191899.png">


Will add explanatory text explaining how your votes relate to the block at the time of the vote was created to the info box at the bottom, where it currently says "You will cast x vote"

**Comment by jounih** [comment]
Does something like this work as copy for the info box:

"You will cast xxx votes, since your token balance was xxx at the beginning of the vote."

With maybe linking "beginning of the vote" text to a snapshot of your token balance on etherscan at the historic block when the vote was created.

**Comment by sohkai** [comment]
We won't be able to directly link to the snapshot directly, but we could link to the snapshot block.

**Comment by sohkai** [comment]
Fixed in #448.
