### ISSUE TITLE
Token manager: add some distinctive visual element in holder list to highlight user's account

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-apps#221]
Rough, easy fix:

![2018-03-29 at 10 40 50 am](https://user-images.githubusercontent.com/447328/38078807-bba6e530-333d-11e8-9564-df21a38be080.png)

We could easily add a badge too!

**Comment by sohkai** [comment]
Yup, been thinking about this but haven't prioritized it. We now get the user's account info pretty easily through aragon.js so this shouldn't be too hard to add to all the apps.

**Comment by izqui** [comment]
No rush, just didn't want this to be lost :)

**Comment by bpierre** [comment]
@sohkai @izqui It’s in this PR https://github.com/aragon/aragon-apps/pull/225
