### ISSUE TITLE
Token Manager: show tokenManager.token() addr for users to be able to directly interact with 

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-apps#228]

**Comment by izqui** [comment]
Alternatively, we could allow apps to expose 'relevant' properties/addresses of them, which could then be seen from the advanced section in settings: aragon#172

**Comment by jounih** [comment]
![WebApp-1366px - Tokens - show address@2x.jpg](https://images.zenhubusercontent.com/5b8ff733fb5dec0b0d9ca453/ef92cfbd-461e-420b-9b96-617c5f6f11c0)

**Comment by chris-remus** [comment]
Changing back to "design: pending", as we're waiting for @jounih to complete the changes we discussed during yesterday's call.
