### ISSUE TITLE
Voting: Display to the end-user the voting option they selected

### ISSUE THREAD

**Issue by stellarmagnet** [aragon/aragon-apps#229]
The voting UI doesn't display the end-user's selected voting option.

There should be a clear visual indicator that displays something like:
**Current Vote**
Yes

**Update Vote**
(Yes) (No) 

Current screenshot:
![image](https://user-images.githubusercontent.com/2584493/38158848-2e6fce06-3451-11e8-854a-4753c094d487.png)

**Comment by jounih** [comment]
Discussed with @chris-remus  and @sohkai - once a user has voted, will replace the yes/no buttons with a "Change my vote" button while the vote is still open. We will also use the info box to say what you voted and how many tokens you cast.

Additionally we should have a visual indicator on the listview showing how you voted on each list item.

Lastly, we should have an error state on the side panel if the vote tx doesn't go through.

**Comment by jounih** [comment]
![webapp-1366px - voting change vote 2x](https://user-images.githubusercontent.com/10109867/45363244-ea15fc80-b5ce-11e8-8698-94bd8eed7990.jpg)

**Comment by jounih** [comment]
Incorporated these points to a voting app UI based on the Survey app - [](https://github.com/aragon/design/issues/10)

**Comment by sohkai** [comment]
Fixed in #448.
