### ISSUE TITLE
Check and test rounding errors calculating returnAmount

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-apps#23]
Given that the calculation has to be done twice, there could be some rounding errors.

We should test to see how significant they are.

https://github.com/aragon/aragon-apps/blob/d4615757447fec2903935b1885129e2e513742ff/apps/fundraising/contracts/Fundraising.sol#L256-L265

**Comment by izqui** [comment]
After giving it another thought I think the loss in precision would be at most 2 * 10^-8 in the minimum divisible amount of a token. In the case of ether or any token with 18 decimals, that would be 2*10^-26.  Am I missing something?

@onbjerg can you check this?After giving it another thought I think the loss in precision would be at most 2 * 10^-8 in the minimum divisible amount of a token. In the case of ether or any token with 18 decimals, that would be 2*10^-26.  Am I missing something?

@onbjerg can you check this?

**Comment by sohkai** [comment]
Closing as the fundraising app is being deprecated.

**Comment by lismore** [comment]
Apologies @sohkai  for dropping the comment here, I have been testing out https://rinkeby.aragon.org and the team I am working with are looking to fundraise & divide ownership of the DAO.  I see examples of a fundraising app in screenshots of the aragon user interface but searching for it looks like it is deprecated.  Where can I find more information about the deprecation.  Is there a repo for the old fundraiser app, is there any guidance on integrating a new way to fundraise within an aragon Democracy DAO.

**Comment by sohkai** [comment]
You can find the [old fundraising app in this repo's history](https://github.com/aragon/aragon-apps/blob/e1f7d0cbf123135c5539faa923cfa72d6b037d67/apps/fundraising/contracts/Fundraising.sol), but that one is particularly outdated and will not work out of the box (nor has it been audited!).

We decided to deprecate it based on learnings about most users wanting to come up with interesting new ways to fundraise, and it would likely be impossible to make something generic enough to suit even the majority of users. The best way for integrating a new fundraising app would be to build one, with the help of the [developer docs](https://hack.aragon.org) :).
