### ISSUE TITLE
Determine what notifications we want

### ISSUE THREAD

**Issue by onbjerg** [aragon/aragon-apps#230]
For the notifications feature to be implemented, we should decide on what notifications we want from each app.

Furthermore, there are technically two types of notifications: "global" and "direct", where global notifications are for all users of a DAO and direct notification is for a specific user or a specific set of users.

We should think about signal/noise ratio when deciding.

**Comment by stellarmagnet** [comment]
Some suggestions:

Global
- [ ] When a new vote is created
- [ ] A "weekly" digest type of notification. Summarizes the "week in the dao" -- new tokens that were assigned, results of votes that were closed, money in/ money out.

User-specific:
- [ ] 24 hour warning before a vote is about to close and you haven't voted

**Comment by sohkai** [comment]
@jounih I think we've made a lot of progress in terms of defining the notification behaviours we want from our last discussion. Would it be possible to write up the notes (not sure where to put it, as it'd act more like a developer guide)?

**Comment by onbjerg** [comment]
Solved?

**Comment by luisivan** [comment]
Yeah, pretty much solved with Camino!
