### ISSUE TITLE
Vault: helper for multi-standard for deposits

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-apps#235]
Currently we have pretty much solved the issue of transferring multi-standard tokens with the same API. However, depositing tokens in the vault requires different logic depending on the token standard.

We might be able to do some nice `delegatecall` here in a way that is not too dangerous for arbitrary token standard deposits to the Vault.

**Comment by chris-remus** [comment]
are you working on this one @izqui? Please assign it to yourself if you are.

**Comment by sohkai** [comment]
Closing since we're reverting the multi-standard vault. We can reopen once we start using the new vault again.
