### ISSUE TITLE
Add numbers to proposals in voting app

### ISSUE THREAD

**Issue by john-light** [aragon/aragon-apps#260]
When you click on the "View Vote" button then it shows you a number for the vote, but it would be nice if you could see a number for the proposal in the main Voting app.

![votescreen](https://user-images.githubusercontent.com/9424721/38968443-61749112-4340-11e8-9d81-f39362c0e7b6.png)

**Comment by sohkai** [comment]
We added this with the card re-design, but then took it out again after some debate in https://github.com/aragon/aragon-apps/pull/560 because starting from 0 was misleading.

**Comment by john-light** [comment]
ok @sohkai since #560 was merged does it make sense to close this now?

**Comment by sohkai** [comment]
I'd say so :).
