### ISSUE TITLE
Finance transfer is not creating transaction.

### ISSUE THREAD

**Issue by john-light** [aragon/aragon-apps#264]
Finance "New Transfer" is not creating transaction. Window closes automatically and does not initiate signing.

Firefox - Linux, Chromium

**Comment by sohkai** [comment]
@john-light do you remember if it was because the user had too many tokens? I think it's related to the math problems in https://github.com/aragon/aragon-apps/issues/266.

**Comment by john-light** [comment]
No it was a general issue, unrelated to the number of tokens. I haven't seen this issue in a while so I will close it.
