### ISSUE TITLE
(Lack of BN.js) Assigning large amounts of tokens does not work

### ISSUE THREAD

**Issue by john-light** [aragon/aragon-apps#266]
If I try to assign myself 1000000 tokens or 1000 tokens it will not start the vote to mint them, but 1 or 100 works. When it doesn't work it does not show any kind of error message.

Apps affected by lack of BN.js:

- [x] Finance
- [x] Token Manager
- [x] Voting

**Comment by sohkai** [comment]
The Token Manager and Finance apps need to use BN.js when calculating the amount of tokens.

**Comment by chris-remus** [comment]
Related to 432.

**Comment by chris-remus** [comment]
Blocked by #432, which will do part.

**Comment by chris-remus** [comment]
@bpierre believes #467 fixed Voting.

**Comment by sohkai** [comment]
Reopening as finance still needs this fixed.
