### ISSUE TITLE
Minting additional tokens to existing multisig tokenholders fails, error unclear

### ISSUE THREAD

**Issue by john-light** [aragon/aragon-apps#269]
Multisig, 3of3, Token Manager, Mint 1 Token to existing tokenholder, 66% Yes so far. I go to vote with the last signature, and get this error in MetaMask: "Transaction Error. Exception thrown in contract code." It is not clear from this error what is going wrong/ why the tx is failing.

**Comment by sohkai** [comment]
Closing for #291. Reason it's failing is because the contract expects token holders in a multisig to always have 0 or 1 tokens.
