### ISSUE TITLE
Show org token name and ticker symbol

### ISSUE THREAD

**Issue by john-light** [aragon/aragon-apps#273]
"Token" label in Token Manager -> should this be or show the org token name and ticker symbol? It should be shown somewhere in the app anyways. (Maybe Settings app too?)

**Comment by sohkai** [comment]
Made https://github.com/aragon/aragon/issues/320 for showing the org name elsewhere in the wrapper.

**Comment by john-light** [comment]
Ok. To be clear, this issue is about the token name and ticker symbol, not the org name.

**Comment by jounih** [comment]
Discussed - will design token badge that has the logo and ticker in non-expanded version

**Comment by jounih** [comment]
![WebApp-1366px - Tokens - token badge@2x.jpg](https://images.zenhubusercontent.com/5b8ff733fb5dec0b0d9ca453/3b7c3b66-fbbb-439d-b763-b0d4b9f15315)

**Comment by chris-remus** [comment]
Changing back to "design: pending", as we're waiting for @jounih to complete the changes we discussed during yesterday's call.

**Comment by sohkai** [comment]
Partly completed by #480, popover component will be added once it's ready in aragon-ui.

**Comment by bpierre** [comment]
To be done when `TokenBadge` will be implemented https://github.com/aragon/aragon-ui/issues/221

**Comment by sohkai** [comment]
Fixed with https://github.com/aragon/aragon-apps/pull/857.
