### ISSUE TITLE
Token transfer succeeds, ETH transfer fails.

### ISSUE THREAD

**Issue by john-light** [aragon/aragon-apps#274]
Democracy org, two token holders, New Transfer in Finance app. SPANK token transfer succeeds, moves on to voting stage. ETH transfer fails, window closes with no indication of what is happening.

**Comment by mnaamani** [comment]
I'm seeing the same issue as well.

**Comment by mnaamani** [comment]
There seems to be a similar behaviour in the TokenManager when trying to assign a large number of tokens, window just closes.

**Comment by john-light** [comment]
@mnaamani thanks for confirming! Regarding that second issue, we have that filed here: https://github.com/aragon/aragon-apps/issues/266

**Comment by sohkai** [comment]
Just realized that this might be a decimal thing, where we're not converting the ETH value correctly (to/from wei as opposed to regular token decimals).

**Comment by chris-remus** [comment]
Pending new DAO kit completion.

**Comment by izqui** [comment]
No longer an issue, ETH transfers and properly working now.
