### ISSUE TITLE
Impossible amounts possible to type in "New Transfer" amount field.

### ISSUE THREAD

**Issue by john-light** [aragon/aragon-apps#275]
Should show an error message and block further action.

**Comment by sohkai** [comment]
@john-light Just to clarify, does "impossible amounts" mean more tokens than what the org has, or just invalid text?

**Comment by john-light** [comment]
More tokens than the Finance app has.

**Comment by sohkai** [comment]
This was actually fixed with #501, pulling it into the mainnet release to test and confirm.

**Comment by izqui** [comment]
Tested and it was indeed fixed.
![ 2018-10-30 at 1.43.01 AM.png](https://images.zenhubusercontent.com/599ac58d8f62dc7798c37e63/bd7ae5bb-6ba2-4363-a505-9ff2b7c94162)
![ 2018-10-30 at 1.43.11 AM.png](https://images.zenhubusercontent.com/599ac58d8f62dc7798c37e63/382168e7-f26a-48ec-9b9e-1b358e8fe58e)
