### ISSUE TITLE
Design an intuitive UX for funding DAOs

### ISSUE THREAD

**Issue by john-light** [aragon/aragon-apps#276]
> The "Send ether to this address" address should be the first and most prominent address

> It is less obvious in the Settings app then it perhaps could or should be.

---------------

The current flow for funding DAOs on rinkeby is quite scary, and hard to find. Users of mainnet DAOs should have an intuitive way to fund their organizations with tokens or ETH, and have it be captured in the finance app.

**Comment by sohkai** [comment]
We could probably swap it with the "Request test tokens" section.

**Comment by sohkai** [comment]
Assigning @izqui to take ownership of designing a proper funding UX with @jounih.

**Comment by john-light** [comment]
Maybe the Finance app could be designed like a wallet app, with a "send" and "receive" button and the receive button can reveal the QR code and address. It is most of the way there, just missing the receive button.

**Comment by jounih** [comment]
Good ideas @john-light . I think the Finance app could work well as a wallet. It needs a friendly mobile design as well - will work on both together.

**Comment by jounih** [comment]
Added proposed UX flow for deposit:

[https://invis.io/7RO21FTHU4G](https://invis.io/7RO21FTHU4G)

**Comment by sohkai** [comment]
Fixed with #527 and #549.
