### ISSUE TITLE
Create a way to delete a user's tokens and remove them from the org

### ISSUE THREAD

**Issue by john-light** [aragon/aragon-apps#279]
There is currently no way to remove a user from an org unless they voluntarily give up their tokens. There should be a way for tokenholders to vote to remove a user from an org and delete/ clawback their tokens.

Requires https://github.com/aragon/aragon.js/issues/120.

**Comment by sohkai** [comment]
The ability to burn tokens in the token manager's contract, but we need to expose this to users via the UI.

**Comment by jounih** [comment]
add action to the overflow menu to remove tokens

**Comment by jounih** [comment]
![WebApp-1366px - Tokens - Remove@2x.jpg](https://images.zenhubusercontent.com/5b8ff733fb5dec0b0d9ca453/c4993e67-20a2-4609-aa89-e151b6466080)

**Comment by chris-remus** [comment]
Changing back to "design: pending", as we're waiting for @jounih to complete the changes we discussed during yesterday's call.

**Comment by sohkai** [comment]
Closed by #480.
