### ISSUE TITLE
Insecure dependencies

### ISSUE THREAD

**Issue by luisivan** [aragon/aragon-apps#323]
We need to bump `hoek` to 4.2.1 everywhere. Looks bad to have a huge warning sign on the repo

> Some of the dependencies defined in package-lock.json, …/token-manager/package-lock.json, …/voting/package-lock.json, …/beta/package-lock.json, …/vault/package-lock.json, and …/payroll/package-lock.json have known security vulnerabilities and should be updated.

**Comment by Kyrrui** [comment]
I can work on this tonight

**Comment by Kyrrui** [comment]
https://github.com/aragon/aragon-apps/pull/326

**Comment by sohkai** [comment]
Closed by #326.
