### ISSUE TITLE
Finance: newPayment radspec description should include destination address

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-apps#333]
https://github.com/aragon/radspec/issues/29

**Comment by john-light** [comment]
This also needs to be fixed in the Voting app.

**Comment by sohkai** [comment]
@john-light not sure what you mean by also fixing this in the voting app.

**Comment by john-light** [comment]
@sohkai the vote signer module should show what the amount and destination address of a payment will be

**Comment by sohkai** [comment]
@john-light Do you mean when someone votes for a payment?

The only place we could probably add the destination address is in the description of the vote.

**Comment by john-light** [comment]
Yes when someone votes for a payment it should be clear what the amount and destination of the payment will be when they go to sign the transaction. Maybe some additional metadata about the payment too (e.g. "For contracting May 1 - May 30, 2018").
