### ISSUE TITLE
Voting didn't close properly

### ISSUE THREAD

**Issue by rainbowjaw** [aragon/aragon-apps#350]
Was testing the current testnet alpha. Didn't check the version, this was a few days ago.

I set up two accounts. One had more voting tokens (over majority)

I set up a vote with the minority token holder (so vote wouldn't clear automatically)
I voted with the second account as a "no"

The vote timer was still running after transaction had cleared and majority was now reached...
I was able to send another vote with majority token holder, and changed my vote to "FOR". The timer stopped, and the vote was a successful yes.

Haven't gotten a chance to try to reproduce this. Even if somehow the required majority was off, shouldn't the vote end when it receives 100% votes?

**Comment by sohkai** [comment]
Hey @rainbowjaw, some notes:

> The vote timer was still running after transaction had cleared and majority was now reached

I think at this point, the vote wasn't in the majority yet? If I understood correctly, the majority token holder voted no here?

> shouldn't the vote end when it receives 100% votes?

I might be misunderstanding, but isn't this what happened in your case, when you changed the majority voter's vote from no to yes?

Our voting app allows voters to change their vote if the vote hasn't been executed yet, so we don't immediately reject the vote in cases where there's still a chance to recover (but we do automatically execute if enough people have voted yes).

**Comment by rainbowjaw** [comment]
> Our voting app allows voters to change their vote if the vote hasn't been executed yet, so we don't immediately reject the vote in cases where there's still a chance to recover (but we do automatically execute if enough people have voted yes).

Ok this was the issue.  I was confused by it, expecting the vote to fail once all votes were cast.
