### ISSUE TITLE
Survey app is loading inconsistently

### ISSUE THREAD

**Issue by john-light** [aragon/aragon-apps#353]
After a few refreshes it might load. But most of the time I just get a page that looks like this:

![aragonsurveyload](https://user-images.githubusercontent.com/9424721/40944085-4b4abcee-6808-11e8-84eb-366c6725da1f.png)

**Comment by sohkai** [comment]
Closing this with the recent changes to which node we're pointing to (now pointing to infura): https://github.com/aragon/aragon/pull/284

In general our websocket connection and node infrastructure isn't the most robust... so this may happen a few times :(.
