### ISSUE TITLE
Survey does not allow you to vote for only one option (at 100%)

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon-apps#359]
From Rocket chat:

> i vote with > 1000 ANT
> when i push " cast your vote" then nothing happen
> when i vote 99% and 1% it's OK

> "What happens when you push it all the way to 100%? Does a transaction still appear?" --> I clicked "cast you vote" but nothing happened, no transaction appear in metamask, nothing change in the website as well

Given what's happening, it's most likely something going wrong when we try to build a transaction. Maybe it's a BigNumber issue with > 1k tokens?

**Comment by sohkai** [comment]
Confirmed it's an issue with > 1k tokens; the number gets serialized in scientific notation rather than a normal number.

**Comment by bpierre** [comment]
Fixed https://github.com/aragon/aragon-apps/pull/310/commits/28dfa459238ce8499d1c62bdda641d4ea7625358
