### ISSUE TITLE
Adding reassurance that signing a vote does not cost tokens

### ISSUE THREAD

**Issue by kingjacob** [aragon/aragon-apps#362]
It might be useful to have a specific callout that says voting in the survey won't cost any tokens.

**Comment by izqui** [comment]
I agree we should add this. 

Maybe even also add some extra reassurance that the transaction that will be sent won't be to the ANT contract but to the survey contract

**Comment by bingen** [comment]
I agree, when we released the survey app and sent it to some friends to test, I was asked that question.

**Comment by sohkai** [comment]
Closed by #747 and #758.
