### ISSUE TITLE
Voting app: Voting panel redesign

### ISSUE THREAD

**Issue by bpierre** [aragon/aragon-apps#369]
A few other issues related to the voting panel (as user stories):

- https://github.com/aragon/aragon-apps/issues/212
- https://github.com/aragon/aragon-apps/issues/216
- https://github.com/aragon/aragon-apps/issues/229
- https://github.com/aragon/aragon-apps/issues/260
- https://github.com/aragon/aragon-apps/issues/261
- https://github.com/aragon/aragon-apps/issues/262
- https://github.com/aragon/aragon-apps/issues/272
- https://github.com/aragon/aragon-apps/issues/366

**Comment by sohkai** [comment]
@bpierre I'd say we can close this issue since we've addressed most of the problems through multiple adjustments to the voting panel, and the tasks left are not directly related to the panel itself.
