### ISSUE TITLE
Build artifact consistency

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-apps#387]
The built frontend for all apps is being saved to `app/build`, except for the Survey app which is being saved to `app/dist`. For reference, the wrapper is also being built to `./build`.

Having some consistency here would be great as it would help simplify our scripts. I don't really care about `dist` vs `build` but I would really like making it consistent.

**Comment by sohkai** [comment]
:+1: we can do that. Not sure exactly why we picked one or the other but consistency is good.

**Comment by sohkai** [comment]
Fixed in #677.
