### ISSUE TITLE
Payroll: bug changing employee salary

### ISSUE THREAD

**Issue by bingen** [aragon/aragon-apps#390]
When changing an employee salary, next withdraw would use the new amount also for the remaining period before the change.

**Comment by izqui** [comment]
I think both this issue and #389 can be solved in a very similar way. We should add a new variable to the employee struct that can keep track of the amount of tokens (denominated in the denomination token) that is owed to the employee, `accruedValue` as suggested by @sohkai. There could also be a role to automatically add more value to this counter for an employee, which would be useful for reimbursements. 

If we do this, we need to stop removing employees from storage when they are terminated and just have a way to flag when was the moment when they stopped accruing value.

**Comment by sohkai** [comment]
Merged with #479.
