### ISSUE TITLE
PayRoll 2.0 or PayWage

### ISSUE THREAD

**Issue by jruffer** [aragon/aragon-apps#391]
We were going to submit a grant proposal to help us with our payroll issues.  We like what is currently going on with this project but it lacks a few of the features we need as a consulting house.  We have both W2 and 1099 on staff.  We would love to add the features for a project based payroll system instead of a straight employee-based system.  

Example: 
Accepted 50 ether for a contract[Vault]. (price ether at $600USD for easy math).
20% transferred to separate account(sales) 10% transferred to separate account(marketing) 70% stays for project budget[Finance]. This 70% is set to units which are submitted by peers for release. In this case, we have 35 ether that we will break into units of 50USD per hour. 21000/50 = 420 units. 
We basically have our project ready to launch.

Peer Alice(1099) requests for 10 units of project work completed. Peer Bob reviewed and accepted. (Units released.) Cindy(w-2) requests 50 units of project work completed. Peer Bob reviewed and accepted. (Units released)

This is our flow and we would love to either fork the current project or add to it via Grant. 

  ##James 
#payroll #grant_discussion

**Comment by sohkai** [comment]
@jruffer In this case, a separate "unit allocation" app for each project probably makes the most sense. You could set the initial parameters (USD/hour rate and amount of ETH to allocate) on initializing the app, and then allow some addresses to request units, pending [insert access control, e.g. a vote or approval by token holder].

**Comment by jruffer** [comment]
Interesting. Would you want us to build that and merge it with the current project? Could we still apply for grant money to add this and other features?

**Comment by sohkai** [comment]
For the grant—depends on the scope of the project, but feel free to send an application to https://github.com/aragon/nest if you think it fits.

Otherwise, there will be small bounties set up for contributing your own apps to a community repo soon :).

**Comment by mariapao** [comment]
Hi @jruffer we fund projects which scope of work needs a funding between $50k and $100k, more or less, so as Brett said, it depends on the scope of the project, and of course, it also depends on what features your are adding. How important they are.

**Comment by sohkai** [comment]
Closing, as this won't be something we will maintain in this repo for the foreseeable future. We will reopen the issue if we consider it again!
