### ISSUE TITLE
Move generic components used in Groups app to aragon-ui

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon-apps#40]
With #16 merged, we should start moving out some of the reusable components to @aragon/aragon-ui.

@bpierre and I identified:
- [x] `Table` and `TableItem` generialized from `Entity`
- [x] `OverlayPanel` (renamed as `SidePanel`)
- [x] `AppContent` / `StyledApp` (packaged together as `DefaultApp`)
- [x] `TopBar` (renamed as `AppBar` or `AppTopBar`?)
- [x] `Field` (able to handle `label`s)
- [x] `EmptyStateCard`
- [x] various components from `FakeShell` useful in @aragon/aragon

**Comment by onbjerg** [comment]
Done?

**Comment by bpierre** [comment]
Yes
