### ISSUE TITLE
Token Manager: add functionality to forcibly move tokens

### ISSUE THREAD

**Issue by lkngtn** [aragon/aragon-apps#419]
When tokens are being used to represent authority within an organization it can be useful for those tokens to be set as non-transferrable. 

This allows for users to use tokens to **represent reputation** within the organization or **membership in hierarchical groups**.

**Comment by izqui** [comment]
The non-transferable flag is set when the Token Manager is initialized and we don't allow changing it (a token cannot be changed from transferable to non-transferable or vice-versa), this is already supported in the Token Manager smart contract. This means that the kit that deploys the DAO needs to configure the Token Manager for non-transferable tokens, in the future this will also be doable from the App Center.

A feature that we could implement is the ability for the Token Manager to transfer tokens from one holder to another (protected behind the ACL). We don't have this yet, but the same functionality can be achieved by burning and minting tokens in the same transaction (using an EVMScript), though it is less optimal.

The only thing needed is to communicate users whether the Token Manager is in transferable or non-transferable mode.

**Comment by sohkai** [comment]
> The only thing needed is to communicate users whether the Token Manager is in transferable or non-transferable mode.

I think this is key, and goes well with providing more information in the Token Manager for users.

> A feature that we could implement is the ability for the Token Manager to transfer tokens from one holder to another (protected behind the ACL). We don't have this yet, but the same functionality can be achieved by burning and minting tokens in the same transaction (using an EVMScript), though it is less optimal.

On the fence about this; I think a nice UX improvement would be a way for users to click a button on the interface to transfer tokens, but that can be done without adding more to the token manager's contract itself. Or are we talking about forcibly moving user tokens through protected actions?

**Comment by izqui** [comment]
@sohkai yep, talking about the Token Manager doing an 'unapproved' `transferFrom` one account to another (which the MiniMe controller can do). This is specially useful for non-transferable tokens that membership in a group, as you can use it to replace members. Again this can be done with in a callscript that performs both burn and mint, but may be clunkier as it would require having both roles.

**Comment by sohkai** [comment]
Verdict on this is to initially provide a UI for accumulating actions (see https://github.com/aragon/aragon/issues/363), rather than building this directly into the Token Manager contract.

**Comment by sohkai** [comment]
Similar to #270, due to the reliance on https://github.com/aragon/aragon/issues/363 this will be removed from the mainnet scope.

**Comment by sohkai** [comment]
Closing; we will evaluate this in future contract upgrades.
