### ISSUE TITLE
Token Manager: display whether the token is transferable or not

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon-apps#423]
In multisig mode, the token is non-transferable. This should be made visible to users.

**Comment by jounih** [comment]
Add this info to Token info

**Comment by jounih** [comment]
![WebApp-1366px - Tokens - Transferrable@2x.jpg](https://images.zenhubusercontent.com/5b8ff733fb5dec0b0d9ca453/faa5e4d1-4a0f-40b0-8779-a79cf558d46c)

**Comment by chris-remus** [comment]
Changing back to "design: pending", as we're waiting for @jounih to complete the changes we discussed during yesterday's call.

**Comment by sohkai** [comment]
Closed by #480

**Comment by sohkai** [comment]
Note that the change in #480 will only show "NO" in organizations using the `aragon-apps@4` versions of the Token Manager contracts.

In earlier Token Manager iterations, the app itself controlled whether the token would be transferrable rather than directly setting it in the token.
