### ISSUE TITLE
Voting: making inequality for passing votes strict?

### ISSUE THREAD

**Issue by bingen** [aragon/aragon-apps#427]
Related to https://github.com/aragon/governance/issues/32#issuecomment-416337704
It makes sense for Democracy DAOs but it doesn't for Multisigs, as @sohkai pointed out, e.g., a 2 out of 4 signatures Multisig would require the inequality not to be strict to easily set up a 50%.
An option would be to add a boolean initialization parameter to indicate how inequalities (for both quorum and support) should behave (something like `bool strictThresholds`), which would be set up to by default to `true` for Democracy DAO kit and to `false` for Multisig.
Opening this issue for discussion.

**Comment by sohkai** [comment]
> A boolean initialization parameter to indicate how inequalities (for both quorum and support) should behave (something like bool strictThresholds)

I like this as an interim solution to making the voting app more generic in general :).
