### ISSUE TITLE
Allow to perform actions as token holder with tokens held in Vault

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-apps#45]
Sometimes the tokens being held in the Vault do not have only economic value, but also allow the holder (the DAO) to perform some actions such as voting or requesting dividends.

A way to forward actions to other contracts as the Vault to perform actions as the token holder is needed.

A more elegant approach would be just a flow of doing an approve/transferFrom with the contract that wants to perform the action as the holder, and at the end return the tokens back to the Vault. This approach wouldn't work to vote with MiniMe tokens, given that the balance is checked at a particular block height.

**Comment by izqui** [comment]
Deferring this to another version of the vault. It isn't really critical for 0.5.

**Comment by sohkai** [comment]
This will be done with the Actor app (see #580).
