### ISSUE TITLE
Support Voting app 2.0.0 contract changes

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-apps#465]
- `getVote()` now also returns the local `supportRequiredPct` for the vote. We should display this value in the panel.
- Both thresholds are now strict, support and quorum must now be greater than the threshold, equality no longer passes.
- #434: `metadata` and `creator` are no longer part of the state, and need to be fetched from logs. Also applies to Survey.

**Comment by sohkai** [comment]
> getVote() now also returns the local supportRequiredPct for the vote. We should display this value in the panel.

This will require us to get the information in the background script, and to render the view based on each vote's local value rather than the global value.

> Both thresholds are now strict, support and quorum must now be greater than the threshold, equality no longer passes.

This will require changes in the user guide, and may also require rewording of the onboarding screen.

**Comment by chris-remus** [comment]
Revisit Friday in context of Token Manager progress. Could be a good issue for @bpierre to work on during trial week next week.
