### ISSUE TITLE
Allow execution of callscript on votes not passing

### ISSUE THREAD

**Issue by onbjerg** [aragon/aragon-apps#47]

**Comment by izqui** [comment]
This has to be a variable of the voting app, but we cannot set it in every vote, as it would allow to execute anything regardless of vote result.

**Comment by onbjerg** [comment]
@izqui Can we just put this in the icebox for a moment? We might solve the actual issue another way, the more we've talked about this one the more uneasy I feel adding it

**Comment by izqui** [comment]
Yes, removing it from the code freeze milestone for the moment

**Comment by sohkai** [comment]
A thought for the future: would it be possible to do this by standardizing a "failure" case in the forwarders? Right now, only the voting app can "fail" forwards (every other app just automatically approves a forward, given correct discovery mechanisms) but there will likely be more apps in the future that will require user interaction for approvals.

We can handle this via an override in the forwarder's interface:

```
function forward(bytes _actionEvmCallScript) public
function forward(bytes _actionEvmCallScript, failureEvmCallScript) public
```

**Comment by onbjerg** [comment]
@sohkai Yes that was discussed, too, but the issue is that the two callscripts have to be different.

Intuitively one would think that just checking if the two callscripts are different would suffice, but they might be different and still produce the same outcome.

Consider for example an attacker that would want to send funds from the Vault to their address. They would create a vote with a callscript that does this on success, but on failure it would transfer to e.g. a simple contract that sends funds it was given to his address.

In this scenario, he would receive funds regardless.

**Comment by izqui** [comment]
Yes, my idea is that this reject callscript could be a state variable of the voting app that gets executed on failure of all votes. This isnt that useful before we can pass parameters/attributes to callscripts (related #166 and #161)

**Comment by onbjerg** [comment]
I think generalizing it with something where forwarders call a standard function (`reject`? `failedForward`?) with some standardized data (a unique identifier for the app? or `keccak256` of the failed script?) would be beneficial.

**Comment by onbjerg** [comment]
Maybe something like

1. Send tx that encodes `forward(script)` to voting app (![A_v](https://latex.codecogs.com/gif.latex?A_v)) from staking app (![A_s](https://latex.codecogs.com/gif.latex?A_s))
2. ![A_v](https://latex.codecogs.com/gif.latex?A_v) calls `attachMetadata(keccak(script), voteId)` on ![A_s](https://latex.codecogs.com/gif.latex?A_s)
    - ![A_s](https://latex.codecogs.com/gif.latex?A_s) MAY store the attached metadata for further reference
3. ✨ Time passes ✨
4. Iff...
    - Vote fails then ![A_v](https://latex.codecogs.com/gif.latex?A_v) MUST call `reject(keccak(script))` on ![A_s](https://latex.codecogs.com/gif.latex?A_s)
    - Vote succeeds, then ![A_v](https://latex.codecogs.com/gif.latex?A_v) MUST call `runScript(script)`

**Comment by luisivan** [comment]
I love your notation @onbjerg

**Comment by izqui** [comment]
I have a feeling that this might work too, maybe it could even be generalized as a 'forwarding feedback protocol', in which you can expect a callback with some data after performing a fwd.

Is `attachMetadata` only called back to when the vote is created?

**Comment by onbjerg** [comment]
@luisivan thanks man

@izqui Well that's sort of an open issue, as I mentioned in an edit:

>If this should work, then how frequently do we call `attachMetadata`? For example, for this to work, the act of voting must also call back (if the caller is a forwarder contract) with the vote ID, which might be super gas intensive.

PS: ye boi

**Comment by sohkai** [comment]
Closing; this is not directly in scope for an additional improvement on top of the current Voting app or aragonOS forwarding structures, and is generally difficult to avoid abuse.
