### ISSUE TITLE
Strings that are called Actions on the App Permissions screen are called Roles in the Permissions landing page

### ISSUE THREAD

**Issue by john-light** [aragon/aragon-apps#475]
The terminology is inconsistent throughout the app. The strings we call "actions" in some places are also called "roles" in others. For example, the "action" string is the human readable interpretation of the "role identifier" string. It would make more sense to either call the "role identifier" the "action identifier", or vice versa call the "action" the "role" instead.

See screenshots for examples of the inconsistent ways this terminology is used.

![permission_role2](https://user-images.githubusercontent.com/9424721/46729002-6bbb8180-cc84-11e8-8985-a354ea7da1f1.png)
![permission-role1](https://user-images.githubusercontent.com/9424721/46729003-6bbb8180-cc84-11e8-883e-f54097467577.png)

**Comment by luisivan** [comment]
Let's side with permissions, instead of roles. Role is a word used mostly by developers when creating their apps, but it shouldn't be called that way for users

**Comment by john-light** [comment]
@luisivan  are you suggesting we replace both "action" and "role" with "permission" throughout the app?

**Comment by luisivan** [comment]
@john-light made a proposal here https://github.com/aragon/aragon/issues/385. Also, we should just remove the word role and the identifier https://github.com/aragon/aragon/issues/384

**Comment by sohkai** [comment]
@john-light going to close this so the discussion can be held at one place in https://github.com/aragon/aragon/issues/385.
