### ISSUE TITLE
Identify Voting app

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-apps#478]
Currently the Voting app doesn't set an identification label for itself, which makes it very hard to differentiate when there are multiple instances:

<img width="205" alt="2018-10-11 at 2 49 20 pm" src="https://user-images.githubusercontent.com/447328/46805261-ebb91880-cd64-11e8-8270-4c23847698a0.png">

<img width="340" alt="2018-10-11 at 2 51 08 pm" src="https://user-images.githubusercontent.com/447328/46805348-1a36f380-cd65-11e8-903a-fa8f67b38ff0.png">

My proposal would be for it to be identified with the token symbol and the support required: `ANT 50%`

cc @lkngtn @luisivan @jounih

**Comment by bpierre** [comment]
It might be a bit confusing to have the support % without indicating of what it is 🤔

**Comment by jounih** [comment]
I don't think the support % is relevant for the instance name. I would prefer just token symbol, or token symbol + 0x... - like ANT (0xabc…def).

But after discussing with @bpierre on how this relates to the app bundles idea and apps having more control of how they are displayed in the app menu (https://research.aragon.org/t/should-templates-be-apps/225) maybe we need to take a bit more time before deciding

**Comment by sohkai** [comment]
Closed by #571.

#571 is a stopgap, mostly for AGP-1, but the general solution will likely involve https://github.com/aragon/aragon/issues/483.
