### ISSUE TITLE
Language improvements: use the term Vote instead of "Voting" (when referring to an object)

### ISSUE THREAD

**Issue by stellarmagnet** [aragon/aragon-apps#48]
[updated per @sohkai's feedback to use the term Vote, instead of the previously suggested Proposal]

### Problem
In the current [design of the Voting Dapp](https://scene.zeplin.io/project/59a827960d4c4cb2274007f5/screen/59a827fff2c3894459c5c1fb), the terminology "Voting" is used to describe a proposal-like object, which is a noun. I believe the better terminology to use is "Vote", since "voting" is a verb, hence there are grammatical errors. 

### Proposed Changes
This terminology should be updated throughout Aragon when Voting is used as a noun. For example, the headings such as "Open Votings" or the button "New Voting" within the Voting app, in addition to anywhere else in Aragon that discusses the object, such as the Permissions page, or Bylaws, etc.

### Some stuff that needs more brainstorming
In the left menu, I think the work area can still be called "Voting", as it is fine to use a verb here. But it is debatable. Renaming it "Proposals" may be more consistent with the updated terminology, yet if Polls are included in this work area, it wouldn't totally mesh as Polls are not Proposals. Alternatively, if it was renamed to "Decisions" or "Forum", this language would make it easier to expand the work-area into different topics the DAO is considering, that may not necessarily all be up to voting yet.

**Comment by sohkai** [comment]
Would using "vote" alleviate some of the grammar issues (vs. "voting")?

Anyhow, I think there's a number of pros and cons to using one over the other (you _vote_ on a _proposal_, so this app encapsulates both ideas, but _vote_ is a really obvious name for the action you'll be taking in the app).

**Comment by stellarmagnet** [comment]
@sohkai using "vote" where? e.g. "New Vote" instead of "New Voting"?

**Comment by sohkai** [comment]
@stellarmagnet Yup, anywhere "voting" is attempted to be used as a noun.

**Comment by stellarmagnet** [comment]
@sohkai I like New Vote/Vote! Good call.

**Comment by bingen** [comment]
I'm not native English, but I wouldn't say "voting" is only a verb:
https://dictionary.cambridge.org/dictionary/english/voting
https://www.oxfordlearnersdictionaries.com/definition/english/voting

**Comment by sohkai** [comment]
Interesting, I'd say from a North American perspective, I've never heard of "voting" used as a noun, but maybe it's an older or British thing.

**Comment by bingen** [comment]
Well, no idea, but as I said I'm not a good reference at all ;-) So of course perfectly fine with the change.

**Comment by Shukri1** [comment]
Svenska

**Comment by sohkai** [comment]
This has been done in 0.5 :).
