### ISSUE TITLE
Remove staking logic from Token Manager (wrapped mode)

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-apps#50]
The 'wrapped mode' makes the Token Manager too complicated. The wrapping/staking logic would be better separated into other app/s. Token Manager only purpose should be to manage a token it has controller power over. 

A generic staking contract could be done that could also work for other usecases. 

Token Manager loses the notion of having two 'modes' (https://github.com/aragon/aragon-apps/blob/master/apps/token-manager/contracts/TokenManager.sol#L66), and everything specific to wrapped mode needs to be gone.

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xd6c1798320bbab6873f93bc2347c90001423fba143e4e788134ec1d530759a67](https://etherscan.io/tx/0xd6c1798320bbab6873f93bc2347c90001423fba143e4e788134ec1d530759a67)
