### ISSUE TITLE
Execution of votes aren't automatic

### ISSUE THREAD

**Issue by john-light** [aragon/aragon-apps#505]
After a vote is approved, it enters a "pending execution state". A final transaction is needed to "execute" the vote. Is there a way we can automate this?

Problems with the current model:
- Users might not know they need to send a final transaction to execute after the vote is over.
- Multiple users might try to execute the vote at the ~same time, wasting gas and block space.

How can we solve this in the most elegant way possible?

**Comment by john-light** [comment]
@izqui says:

> votes can be executed by anyone after they timeout so we DAOs (or ourselves) could have a daemon that just executes as soon as they can be
> someone else should run it and we could sponsor it for some time
> I worked on a generic daemon that was needed for AGP23 https://github.com/aragonlabs/AGP23/pull/1/files/#diff-f06f958a98d7530cd890cb59806c8137
> the idea is to have function that anyone could call and if it suceeds they can get rewarded

**Comment by sohkai** [comment]
Closing; the daemon service is unrelated to the apps themselves and should be provided separately.
