### ISSUE TITLE
Remove token failed

### ISSUE THREAD

**Issue by john-light** [aragon/aragon-apps#507]
I have two members in my org. I used one of the member accounts to try and remove the other member. The app gave me this error:

![aragon_remove_token_fail](https://user-images.githubusercontent.com/9424721/47214414-28f15c00-d39e-11e8-95dd-97baa87fb38e.png)

**Comment by john-light** [comment]
@izqui it looks like the "burn tokens" action does not have a manager. But should we show buttons in apps to perform an action that no one can do yet?

**Comment by izqui** [comment]
@john-light certainly not, but this is information apps currently don't have. There is an open issue in aragon.js for exposing this sort of info to apps, which could then use to hide parts of the UI https://github.com/aragon/aragon.js/issues/162

**Comment by john-light** [comment]
@izqui ok thanks, I will close this issue in favor of the one you linked then

**Comment by askeluv** [comment]
Sorry for jumping in here, but what's the recommended way to burn tokens currently? Is it even possible? @izqui @john-light

**Comment by john-light** [comment]
@askeluv see "remove token" in the User Guide here: https://wiki.aragon.org/tutorials/Aragon_User_Guide/#321-holders

**Comment by askeluv** [comment]
@john-light thanks, but there’s no section on «remove tokens» though?

**Comment by john-light** [comment]
@askeluv depending on how your organization is set up you may need to initialize the permission. Go to Permissions > Token Manager > Actions available on this app > Initialize "Burn Tokens" action. Then set a manager and who you want to grant permission to (setting the Voting app for both is a safe call, at least for testing purposes; I recommend trying this on Rinkeby before mainnet). 

Also this convo just made me realize that the Burn Tokens action isn't documented in the Permissions section of the User Guide, so thanks for bringing it up!
