### ISSUE TITLE
New organization shows unknown entities with permissions

### ISSUE THREAD

**Issue by john-light** [aragon/aragon-apps#508]
Just created this organization. None of the entities that look like Ethereum addresses are any of my accounts. What are these accounts?

![permissions_who](https://user-images.githubusercontent.com/9424721/47214964-e4ff5680-d39f-11e8-8fae-b0e08360a27e.png)

**Comment by bingen** [comment]
Yes, I'm pretty sure they are fixed, see here:
- "Create permissions":
https://github.com/aragon/dao-kits/blob/master/kits/democracy/contracts/DemocracyKit.sol#L65
- "Manage apps":
https://github.com/aragon/dao-kits/blob/master/kits/beta-base/contracts/BetaKitBase.sol#L140
- "Mint tokens":
https://github.com/aragon/dao-kits/blob/master/kits/beta-base/contracts/BetaKitBase.sol#L141
- The common function used:
https://github.com/aragon/dao-kits/blob/master/kits/bare/contracts/KitBase.sol#L37

Anyway, I'll add some tests [here](https://github.com/aragon/dao-kits/blob/master/kits/democracy/test/democracy.js#L109) to make sure that they get cleaned.

**Comment by sohkai** [comment]
@john-light Let's double check this with the new contracts when they get deployed to staging :).

**Comment by bingen** [comment]
I now realize that what I said before accounts for the last account `0x344b...`, for the other two ones it should be here:
https://github.com/aragon/aragonOS/blob/dev/contracts/factory/DAOFactory.sol#L59
But as @sohkai said, let's check again with the new deployment.

**Comment by izqui** [comment]
These have been cleaned up with the current release of the kits:

![ 2018-10-30 at 1.48.14 AM.png](https://images.zenhubusercontent.com/599ac58d8f62dc7798c37e63/7c260ff0-47bb-48bd-8ec6-1af5d7947ccf)
