### ISSUE TITLE
Make vote descriptions more user-friendly

### ISSUE THREAD

**Issue by john-light** [aragon/aragon-apps#510]
Currently the vote descriptions have addresses where we could instead show app badges ("Voting App", hover over to see full address) or (once we have the identity app) ENS names for entities. Using badges and ENS names the descriptions become much more easy to read.

![aragon_vote_description](https://user-images.githubusercontent.com/9424721/47219781-1718b480-d3b0-11e8-919c-386a058314cf.png)

**Comment by sohkai** [comment]
And we could also add a "role badge" for permissions bytes!

**Comment by sohkai** [comment]
We now use IdentityBadges and role descriptions in voting descriptions. The only thing left is to use AppBadges in the descriptions: https://github.com/aragon/aragon-apps/issues/1040.
