### ISSUE TITLE
Keep track of all token holders in Token Manager

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-apps#53]
This is an extremely short term solution that will allow the Token Manager frontend to load much quicker. 

Given #51, which allows to have boards with just tokens, a way to quickly a list of all token holders is important.

Adding this will add ~45k gas every time a new holder is added. Expensive but might be worth it in UX terms in the short term.

**Comment by lkngtn** [comment]
What would the longer term solution be that is more gas efficient?

**Comment by izqui** [comment]
Right now the frontend filters all transfer events for the token in the blockchain to compute the list of holders locally, this is probably going to be too resource hungry and not be really performant, specially in heavily transferred tokens. 

The super cool long term solution is the ability to have a 'shared cached state' of apps, so the state is only computed once and then others can use it while minimizing the amount of trust on the entity that serves the state. We will do a lot of effort on this front for v0.6.
