### ISSUE TITLE
Add receiveApproval function to Finance contract

### ISSUE THREAD

**Issue by bingen** [aragon/aragon-apps#56]
As stated in the wiki, in order to deposit ERC20 tokens in Finance app, right now we need 2 calls:
```
token.approve(finance, amount)
finance.deposit(token, amount, string reference)
```
While for ERC677 tokens we just need one:
```
token.transferAndCall(finance, amount, string reference)
```
Adding the function `receiveApproval` would allow to deposit ERC20 tokens using just one call too.

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x1f015dbd1b4756d2bd02d3d4d330aa8ed3b0908223a5d3273befcd022e66af1e](https://etherscan.io/tx/0x1f015dbd1b4756d2bd02d3d4d330aa8ed3b0908223a5d3273befcd022e66af1e)

**Comment by izqui** [comment]
This would make it compatible with non-standard ERC20's 'approveAndCall' method.
