### ISSUE TITLE
Finance: support tokens returning their name and symbol as 'bytes32'

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-apps#561]
For some reason, Dai uses a `bytes32` state variable for its [name and symbol](https://etherscan.io/token/0x89d24a6b4ccb1b6faa2625fe562bdd9a23260359#readContract) 🤷‍♀️

The Finance app doesn't support this edge case and the UI looks confusing right now:

<img width="439" alt="2018-11-03 at 3 17 35 pm" src="https://user-images.githubusercontent.com/447328/47953302-14a38680-df7c-11e8-9893-7f062059f3fc.png">
<img width="1359" alt="2018-11-03 at 3 17 44 pm" src="https://user-images.githubusercontent.com/447328/47953303-18370d80-df7c-11e8-8de3-9d5969d90011.png">

https://mainnet.aragon.org/#/ravedao.aragonid.eth/0xc5ef25d8f0678ddca01e49201cbea521ece81587

**Comment by sohkai** [comment]
#616 and a fallback for `bytes32` (this issue) will be merged together in Finance.
