### ISSUE TITLE
Token balances don't load

### ISSUE THREAD

**Issue by luisivan** [aragon/aragon-apps#569]
Steps to reproduce:
1. Go to one of these organizations https://mainnet.aragon.org/#/circle.aragonid.eth/0x9eba873dbaabec7c9fff1fe85cfe9c6c12af36ea https://mainnet.aragon.org/#/dutchx.aragonid.eth/0xa688d3ca7cadded04fcb62d25db79ef49c1ca7b5 https://mainnet.aragon.org/#/ccde.aragonid.eth/0xe5deaf1cab4a3023eaa22484f0cb7f45c0700a52
2. There should be token balances, as otherwise their organizations would be not usable anymore
3. There aren't any token balances shown

Tried using both Firefox and Chromium on Linux, without injecting any web3 provider.

**Comment by izqui** [comment]
I may be better to fix it in aragonJS, by checking external logs from the app initialization block by default, unless the app explicitly specifies the `fromBlock`
