### ISSUE TITLE
Add function to Finance to send tokens to Vault

### ISSUE THREAD

**Issue by bingen** [aragon/aragon-apps#57]
If accidentally somebody sends tokens to Finance contract address directly through `transfer`, tokens could be locked in that contract as Finance doesn't have a way to send transactions (it's using Vault for that).
My suggestion is to add a function that allows to send all tokens in Finance to Vault anytime.

**Comment by izqui** [comment]
I believe such function doesn't even need to be protected by the ACL, and could be called at any time.
