### ISSUE TITLE
Add "You voted" icon to Voting card

### ISSUE THREAD

**Issue by john-light** [aragon/aragon-apps#578]
> It would be good to have a little "you voted" icon(maybe green check mark in a circle or something) in the Open Votes dashboard in the left hand bottom corner of the voting card.

**Comment by sohkai** [comment]
Hmm, I think @bpierre and @jounih were talking about something like this when we were moving the Voting app to use the card layout. Might've fallen through the cracks though.

**Comment by sohkai** [comment]
@john-light Ah, actually, you can see if you've already voted on a particular vote as there'll be a "You" label next to the option you voted on.

**Comment by john-light** [comment]
Ah yes I see that now! Thanks, closing.
