### ISSUE TITLE
Voting app not allowing a token holder to vote

### ISSUE THREAD

**Issue by john-light** [aragon/aragon-apps#581]
User with address 0x81aaA9a7a8358cC2971B9b8dE72aCCe6d7862BC8 was added to this org https://mainnet.aragon.org/#/dsoe.aragonid.eth/0xf0a0337b46f7b3b198009febeb59d6ed54a35f5a and despite being a token holder cannot vote on this proposal (screenshot is from the user's own computer).

I have made sure that metamask is open to the right account and we tried refreshing/clearing cache - none of these have solved the issue.

![vote-error](https://user-images.githubusercontent.com/9424721/48824903-95070d00-ed1a-11e8-9acd-4f51b0046986.png)

**Comment by sohkai** [comment]
Assuming this was a one-off issue; it was likely a broken connection, our ETH node being slow, or the user not selecting the correct account or network on their Ethereum provider.
