### ISSUE TITLE
Change "New vote" to "New poll"

### ISSUE THREAD

**Issue by john-light** [aragon/aragon-apps#582]
In the voting app the button says "New vote" and that "Votes are informative". But the binding votes are also called "votes", so calling these the same thing while defining them differently is confusing.

What is called a "vote" in the "New vote" panel should really be called a "poll", since it is an informative question with a simple "yes" or "no" answer.

![screenshot_2018-11-21 aragon](https://user-images.githubusercontent.com/9424721/48868670-49427b00-ed8f-11e8-9098-a1292b5c1d4e.png)

**Comment by dev1644** [comment]
Hi, So should "New Vote" should be called "New Poll" and "Votes are informative" to "Polls are informative"?

**Comment by luisivan** [comment]
We could also add an informative message saying that if you wanna do any binding action such as withdrawing funds or minting tokens, those don't belong in a poll
