### ISSUE TITLE
Inaccurate string in the "New vote" panel

### ISSUE THREAD

**Issue by john-light** [aragon/aragon-apps#583]
When you click the "New vote" button in the Voting app, at the bottom it says:

> By opening this vote, you will automatically vote yay.

However this is not true anymore. When I created a new vote I had to add my vote afterwards.

**Comment by sohkai** [comment]
@john-light I'd say this will be fixed with https://github.com/aragon/aragon-apps/issues/416. That would allow someone to choose if they automatically vote or not.
