### ISSUE TITLE
View organisation funds (Agent app functional requirement: General)

### ISSUE THREAD

**Issue by dizzypaty** [aragon/aragon-apps#585]
As an Aragon DAO participant or group of participants, I would like to have a view of the specific DAO funds so I can know the DAOs balance at all times.

Please refer to the [project PRD](https://www.notion.so/Agent-app-PRD-Product-Requirement-Document-06cfd6944f4e4c58ad9bb4fe3877d618 ) for more detailed information.

**Comment by sohkai** [comment]
Closing, as the Agent app has a design spec now.
