### ISSUE TITLE
Agent: withdrawal funds

### ISSUE THREAD

**Issue by dizzypaty** [aragon/aragon-apps#588]
As an Aragon DAO participant or group of participants, I would like to manage assets by creating a new transfer so I can withdrawal funds in the Vault app.

Please refer to the [project PRD](https://www.notion.so/Agent-app-PRD-Product-Requirement-Document-06cfd6944f4e4c58ad9bb4fe3877d618) for more detailed information.

**Comment by sohkai** [comment]
Closing, as the Agent has a product design spec now.
