### ISSUE TITLE
Browse list of performed / past actions (Agent app functional requirement: Actions)

### ISSUE THREAD

**Issue by dizzypaty** [aragon/aragon-apps#591]
As an Aragon DAO participant or group of participants, I would like to browse the list of performed / past actions so I can analyse and understand the DAOs activity.

Please refer to the [project PRD](https://www.notion.so/Agent-app-PRD-Product-Requirement-Document-06cfd6944f4e4c58ad9bb4fe3877d618) for more detailed information.

**Comment by sohkai** [comment]
Closing, as the Agent app has a design spec now.
