### ISSUE TITLE
View actions details in Etherscan (Agent app functional requirement: Actions)

### ISSUE THREAD

**Issue by dizzypaty** [aragon/aragon-apps#593]
As an Aragon DAO participant or group of participants, I would like to view / access more detailed information of a performed / past action in Etherscan 

Please refer to the [project PRD](https://www.notion.so/Agent-app-PRD-Product-Requirement-Document-06cfd6944f4e4c58ad9bb4fe3877d618) for more detailed information.

**Comment by sohkai** [comment]
Closing, as the Agent app has a design spec now.
