### ISSUE TITLE
Agent: set conditional permissions for actions

### ISSUE THREAD

**Issue by dizzypaty** [aragon/aragon-apps#594]
As an Aragon DAO participant or group of participants, I would like to set conditional permissions for the actions I create 

Please refer to the [project PRD](https://www.notion.so/Agent-app-PRD-Product-Requirement-Document-06cfd6944f4e4c58ad9bb4fe3877d618) for more detailed information.

**Comment by lkngtn** [comment]
This conversation has come a bit and it seems like it would be necessary to define a "whitelist" of actions.

This present a couple of questions I think are worth exploring:

1. If a function is added to the whitelist (do we have any ability to evaluate the parameters which are passed to the function?)
2. If we are managing a whitelist of functions what is the flow in the organization for protecting those functions by different permissions?

**Comment by sohkai** [comment]
Closing; we will evaluate adding permissions for the Agent's `execute()` action in the future.
