### ISSUE TITLE
Agent: represent the identity of the organisation

### ISSUE THREAD

**Issue by dizzypaty** [aragon/aragon-apps#595]
As an Aragon DAO participant or group of participants, I would like to use the DAOs identity on my behalf.

Please refer to the [project PRD](https://www.notion.so/Agent-app-PRD-Product-Requirement-Document-06cfd6944f4e4c58ad9bb4fe3877d618) for more detailed information.

**Comment by sohkai** [comment]
This has come up a few times; we may want to change the ENS name currently being assigned to the org's Kernel to instead be assigned to the Agent app (if available).

It is fairly easy for us to get back to the Kernel from an app, and doing this would allow users to send ETH and tokens directly to the org's ENS name. It would also allow the org to manage their ENS name.

**Comment by sohkai** [comment]
We will re-evaluate where an organization's ENS name gets set when we need to create and deploy new templates.
