### ISSUE TITLE
Add way to find/recognize foreign token deposits

### ISSUE THREAD

**Issue by MidnightLightning** [aragon/aragon-apps#597]
If a deposit is initiated from the Finance app, the string referencing going along with the deposit can get properly saved (and the actual transfer is done by the ERC20 `transferFrom()` function). 

However, if someone sends ERC20 tokens directly to the Finance app (an airdrop, or someone who didn't think to go through the Finance app UI), those funds are under the authority of the Finance app, but there's no way to tell the Finance app to take notice of it.

What would be helpful is to have some sort of `checkTokenBalance(address tokenAddress, string reference)` method on the Finance app that caused the Finance app to check the `balanceOf` function on the destination `tokenAddress`, compare that against its own internal ledger of how much of that asset it thinks it should have, and if there is more than expected, log it as a new deposit (with `reference` as the detail), such that the UI agrees with the token's smart contract as to the Finance app's balance.

**Comment by sohkai** [comment]
Closing for https://github.com/aragon/aragon/issues/496. Technically, it'd be better if you _recovered_ the tokens into the organization's vault, as any funds stuck on the app proxies are unusable.
