### ISSUE TITLE
Set up code coverage

### ISSUE THREAD

**Issue by onbjerg** [aragon/aragon-apps#6]

**Comment by izqui** [comment]
I think it would be important to have one coverage metric for the entire repo. Can we trick this by having a `test` directory at the root level with symlinks to the actual test files?

Another consideration is how we share test helpers (web3 helpers, assertThrow...), as we shouldn't have those files copied in each package.

**Comment by onbjerg** [comment]
>Another consideration is how we share test helpers (web3 helpers, assertThrow...), as we shouldn't have those files copied in each package.

I think we should try to isolate the packages as much as possible, but thinking about it we might not need to since we would never actually publish the packages on npm.

Can you open up an issue about it since it's a separate topic?

>I think it would be important to have one coverage metric for the entire repo. Can we trick this by having a test directory at the root level with symlinks to the actual test files?

I don't think we need to do symlinks, but the plan is definitely to have a single code coverage metric for the entire repository. We could look at how [Babel](https://github.com/babel/babel) does it.

**Comment by izqui** [comment]
Tests are passing on all apps now https://travis-ci.org/aragon/aragon-apps/jobs/291188419

For test coverage we could individually run solidity-coverage on every package and then somehow concat all `lcov.info` files to produce just one coverage report. Would this work?

**Comment by izqui** [comment]
This should do the job: https://github.com/mweibel/lcov-result-merger
