### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon-apps#602]
`lerna bootstrap` is causing the CI to fail because it takes too long to install.

The best way to solve this right now is likely to have a `install:contracts` command that ignores each app's frontend installation as we don't currently test them. This could be done via a separate install script that checks if a given env var is on (e.g. `INSTALL_FRONTENDS`) before going ahead and running `npm install` in the app's dir.

**Comment by stefanionescu** [comment]
Also have problems with lerna. Gets stuck at @aragon/apps-finance
![aragon](https://user-images.githubusercontent.com/15263515/49961948-97751500-ff1c-11e8-8b46-b15038f2ee54.png)
