### ISSUE TITLE
Move 'fundraising' out of apps directory

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-apps#61]
As we are not shipping this app in the first release of v0.5, make it easier for readers and auditors to know it is not part of the release

**Comment by sohkai** [comment]
Do you think it should still be audited, or that we'll be changing it so much (i.e. simplifying it a lot) that it's not worth it?

I wouldn't mind just a big README heads up instead if it'll still be audited.

**Comment by izqui** [comment]
Won't be audited, that's the main reason it has been moved
