### ISSUE TITLE
Finance: Increase gas limit for deposits when period transitions are required

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-apps#621]
I believe we are hard-coding 420k gas for Finance deposits, which is not enough for gas ineficient tokens MiniMe tokens like ANT ;)

See OOG tx: https://etherscan.io/tx/0xecf9f14c061f8c78d146188faaefefe59da5032f30ada1f609c61631aa360b5f
Successful tx: https://etherscan.io/tx/0x2f5fee79913036a409e00778848c8b746ac29f9027fde58f05a408f847baf79c

We should test whether increasing it to 450k is enough, though I would add a bit more of breathing room increasing it to 500k gas.

**Comment by sohkai** [comment]
Wish we had it at 420, but it's [close](https://github.com/aragon/aragon-apps/blob/master/apps/finance/app/src/App.js#L82). We should increase it to `500000`.

**Comment by sohkai** [comment]
Actually the gas estimation for the deposit itself isn't problematic; what's problematic is that we're not accounting for period transitions in that gas calculation (~80k gas per period transition due to four possible `SSTORE`s, might as well fudge to 100k per transition).

**Comment by izqui** [comment]
Oh, good catch lol
