### ISSUE TITLE
Finance: allow copying addresses from the 'Source/Recipient' column

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-apps#622]
In Chrome I am unable to select the text in the entity component in 'Source/Recipient' which would be quite convenient for copying an address for doing a deposit or withdraw with a previous address.

**Comment by sohkai** [comment]
I think the idea of the AddressBadge is that you'd be able to [click on it to get the full address with a copy button](https://github.com/aragon/design/issues/3). This will be solved when the full AddressBadge is implemented (now unblocked with the first iteration of the Popover component).

**Comment by sohkai** [comment]
Closed by #642.
