### ISSUE TITLE
Voting: single delegation

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-apps#623]
Started working on an issue here but ended up posting it to the forum so we can have the discussion there until some basic questions have been addressed.

https://forum.aragon.org/t/voting-v1-single-delegation/440

I think we could start doing some UX research and UI work already @jounih @dizzypaty 

cc @lkngtn @bingen @sohkai

**Comment by jounih** [comment]
Cool! Let's sync on scheduling this design work on today's design call @dizzypaty

**Comment by sohkai** [comment]
Contract completed in #881.

**Comment by sohkai** [comment]
We will track this effort in https://github.com/aragon/aragon-apps/issues/1101, as it requires contract upgrades.
