### ISSUE TITLE
Token Manager displays "Transferrable: Yes" when token is not transferrable. 

### ISSUE THREAD

**Issue by lkngtn** [aragon/aragon-apps#630]
When setting up a custom organization using the CLI I noticed that there appears to be a bug in how we display wether a token is transferrable in the token manager. 

Steps to reproduce:

Create a minime token which is transferrable:

`dao token new  [name] [symbol]`

Install but do not initialize the token manager:

`dao install [dao] token-manager --app-init none`

Set the token manager as the controller for the minime token

`dao token change-controller [token] [token-manager]`

Set a permission on the token manager, eg MINT_ROLE

`dao acl create [dao] [token-manager] MINT_ROLE [self] [self]` 

Initialize the token manager as non-transferrable

`dao exec [dao] [token-manager] initialize [token] false 0`

<img width="283" alt="image" src="https://user-images.githubusercontent.com/4986634/51418743-3fe94b00-1b53-11e9-9dd0-3bd3ec5b94a8.png">

The token manager shows as transferrable, but trying to transfer the token will fail:

<img width="986" alt="image" src="https://user-images.githubusercontent.com/4986634/51418754-542d4800-1b53-11e9-8cad-60f7d970d1bf.png">

**Comment by sohkai** [comment]
@lkngtn Can you point me to a org that was set up this way? Fairly, fairly certain this shouldn't be messing up since we read from the token what its transferable status is.

> As a side note: it's confusing that you can set the token itself as transferrable or non-transferrable, and at initialization set the token manager as transferrable or non-transferrable. Its not clear which option should be used or why.

Agreed this is kind of awkward. The Token Manager actually _overrides_ the transferable status of the token on initialization; it checks to see if the status matches what you gave it, and if it doesn't, changes it to be so. I can only think of this being useful in kits that expect a token input, so that the orgs they create have the same token transferability status.

**Comment by lkngtn** [comment]
> @lkngtn Can you point me to a org that was set up this way? Fairly, fairly certain this shouldn't be messing up since we read from the token what its transferable status is.

https://mainnet.aragon.org/#/0x940B2B518F761f4c52CDd9865C57D9a907DC5E82/0xe195cb39cd32c8692bb5e549016288c3343850f0

**Comment by sohkai** [comment]
@lkngtn Looked into this; the app isn't lying; the token is transferable. In the screenshot above, the gas limit was too low for the call to succeed (minime transfers cost usually ~120k).

Both of the tokens are transferable; the CLI must not have used the params correctly :(

**Comment by lkngtn** [comment]
Reopening this due to a comment from [Adamstallard on the forum](https://forum.aragon.org/t/guide-custom-aragon-organization-deployment-using-the-cli/507/14): 

> It’s not just a display issue. You can always transfer the tokens if you set the gas limit high enough. See https://github.com/aragon/aragon-apps/issues/630 . I have confirmed that tokens are transferable even after setting transferable to false for the token new and dao exec command (to initialize the token manager.)

> Both of the tokens are transferable; the CLI must not have used the params correctly :(

I'm not sure how this would be an issue with the CLI since as far as I can tell it would need to be an issue with the `dao exec` command, it is not doing any special handling of these parameters for token transfers specifically, so if its an issue then all boolean parameters passed through `dao exec` would have issues? @0xGabi can you confirm?

**Comment by 0xGabi** [comment]
@lkngtn was able to figure out what's going on. Is about the optional argument [`transfer-enable`](https://github.com/aragon/aragon-cli/blob/master/packages/aragon-cli/src/commands/dao_cmds/token_cmds/new.js#L22). We miss the `boolean: true` configuration so false was recognized as a string and coerce as true. I will submit a PR to fix this, thanks for reporting it

**Comment by 0xGabi** [comment]
I found that `dao exec` keep parsing the `false` argument as `true` on the initialize function of the Token Manager app. I'm still testing and looking for the possible reason behind it, it seems related with `yargs-parser`

**Comment by sohkai** [comment]
@0xGabi Closing this issue since it's not related to the apps but is an CLI issue.

@0xGabi has also opened a draft PR to fix this in the CLI: https://github.com/aragon/aragon-cli/pull/555.
