### ISSUE TITLE
[TokenManager] Update or remove confusing package.json npm deploy scripts

### ISSUE THREAD

**Issue by ottodevs** [aragon/aragon-apps#631]
It seems that some deployments scripts are not used anymore, since they are using syntax from 10 months ago, those should be removed or updated since they may be confusing for newcomers getting inspired by official apps code:

https://github.com/aragon/aragon-apps/blob/fa6e64685b7801fb1b0a0f5819b145cb020087e8/apps/token-manager/package.json#L14

**Comment by sohkai** [comment]
Closing for #563.
