### ISSUE TITLE
Voting: add badge to describe the voting instance

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon-apps#633]
Would be nice if the Voting app had a badge, similar to the Token Manager (see below), to give the user more information about that particular instance (e.g. token used, approval %, etc). Related to https://github.com/aragon/aragon/issues/89.

cc @aragon/design

**Comment by dizzypaty** [comment]
I think this is a great suggestion – I'm hoping to review soon the way we display purple badges throughout the app and define their usage. We could also add an informative section, similar to the Token Manager, where we display that particular app instance information.

**Comment by sohkai** [comment]
Superseded by #713.
