### ISSUE TITLE
Give parameters a role that allows updating them

### ISSUE THREAD

**Issue by john-light** [aragon/aragon-apps#634]
From @lkngtn: 

> I think we should try and avoid parameters which can only be set at initiation as much as possible, and instead have a role that allows updating them. The manager of this role can be discarded, essentially making the parameter immutable.

@sohkai replies:

> We can start going down this path more and more, given the number of headaches we've had trying to adhere to our "strict" nothing-can-change-underneath-you model for the apps.

I reply to to @sohkai: 

> If the concern with removing "nothing-can-change-underneath-you" model is one of security, perhaps the client could show the user some visual indication that the app has changed? A couple of ideas come to mind like a "This app has updated since you last used it." banner that the user can close after seeing and "Last updated on [date]" in the corner or somewhere out of the way but easy to find.

https://github.com/aragon/AGPs/pull/15#issuecomment-456116452

**Comment by bingen** [comment]
Adding the context of a related previous discussion here too:
https://github.com/aragon/aragon-apps/pull/98#pullrequestreview-97927732

**Comment by sohkai** [comment]
Closing; we will introduce the ability to change parameters as necessary.
