### ISSUE TITLE
Run tests in geth and parity

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-apps#64]
Same as https://github.com/aragon/aragon-core/issues/171

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x980c5e0473f65dcfaa9249f954f578e0013838aeb420455073cc9f46105c2d82](https://etherscan.io/tx/0x980c5e0473f65dcfaa9249f954f578e0013838aeb420455073cc9f46105c2d82)

**Comment by cpurta** [comment]
@izqui, would like to take this one on.

**Comment by izqui** [comment]
Awesome! It should be pretty easy to migrate to aragon/aragon-core#171 later :) Will fill the bounties tomorrow

**Comment by sohkai** [comment]
Closing, as mentioned in #66, this is not a short-term priority.
