### ISSUE TITLE
Voting: token holder unable to vote

### ISSUE THREAD

**Issue by akru** [aragon/aragon-apps#640]
In https://github.com/aragon/aragon-apps/blob/master/apps/voting/contracts/Voting.sol#L278 used block `number - 1`, in could block voting process when voter will added in the same block. Because it use `votingPower` at current block https://github.com/aragon/aragon-apps/blob/master/apps/voting/contracts/Voting.sol#L272.

**Reproducing scenario**

1. mint voter token for some voter account
1. in same block start voting on some question
3. new voter is accounted in quorum but can't vote

**Comment by sohkai** [comment]
Using `blockNumber - 1` is a deliberate choice to avoid potential double votes when someone votes and then moves their tokens in the same block.

**Comment by akru** [comment]
Ok, but don't change this isn't so good. May be use `blockNumber - 1` in https://github.com/aragon/aragon-apps/blob/master/apps/voting/contracts/Voting.sol#L272 will be better?
