### ISSUE TITLE
Add gas reporter for tests

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-apps#65]
https://github.com/cgewecke/eth-gas-reporter

It would be awesome to know how much gas our tests are taking.

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x7bec266b14ae6098b0806f206f978bb658323b5e5f0533b434665d00925b28a5](https://etherscan.io/tx/0x7bec266b14ae6098b0806f206f978bb658323b5e5f0533b434665d00925b28a5)

**Comment by linuxchip** [comment]
@izqui , i am interested to check on this. Thanks

**Comment by cpurta** [comment]
This would be awesome. Would be especially helpful to know how much gas the development network will need for testing being implemented in #66.

**Comment by cpurta** [comment]
Looks like the bounty contract was never funded.

**Comment by onbjerg** [comment]
@izqui
