### ISSUE TITLE
Funding with EOS-style crowdsale application

### ISSUE THREAD

**Issue by litvintech** [aragon/aragon-apps#653]
Hello, guys. We are [cybercongress](https://github.com/cybercongress/) and we are using Aragon: our id is [cyberfoundation.aragonid.eth](https://mainnet.aragon.org/#/cyberfoundation.aragonid.eth/0xf4d85b5a1650a335b30072d178f6dcb611f05a3e)
We need application wich allow as continiuosly collect funds and distribute CDB token. For example like EOS did it with their Ethereum based crowdsale.
May you, please, briefly introduce integration flow of this app into existing Aragon's application stack

**Comment by sohkai** [comment]
Hey @litvintech, providing a fundraising app is not something that's on our current roadmap at the moment, but you can very easily create your own ([see documentation](https://hack.aragon.org/))!

**Comment by sohkai** [comment]
@litvintech Aragon Black is working on a [new fundraising app](https://github.com/aragonblack/fundraising), you may want to check in with them!
