### ISSUE TITLE
Agent: add ability to guard against token transfers

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon-apps#656]
Given the security implications of the Agent app's `execute()` functionality, it would be nice if users had a way to ensure that their ETH and token holdings are consistent before and after the call (such that no transfers happened, or if they did, at least their app's balance wasn't changed).

This doesn't scale generally, but we could allow users to add token addresses onto a list that we check balances of before and after each invocation of `exeucte()` if the user specified it (either as an argument or another function, e.g. `dangerousExecute()`). For most users, I can imagine this list to be quite small (DAI, ANT, etc.), at least for now. ETH is already taken care of by the existing contract as it's only transferred based on an argument.

Note that the forwarding functionality wouldn't be able to be protected by this, as it doesn't yet accept an input. This is protected under another role that is meant to be higher-privileged than `execute()`'s, and so I would always treat it as `dangerousExecute()`.

cc @lkngtn

**Comment by izqui** [comment]
I thought about guarding against `approve` and `transfer` signatures but it really doesn't seem like a good idea to me.

**Comment by lkngtn** [comment]
The token list check approach seems reasonable, I suspect that even a limited list of tokens would be sufficient for most cases. 

This would not be sufficient to prevent all token transfers or to prevent asset transfers for things like NFTs, but in cases where we know there are specific assets we care about not being transferred then this should provide relatively strong protections. I think this might be a good solution to voting with bonding curve collateral (cc @osarrouy) 

It also reminds me a bit of https://marble.org, which I thought was a pretty interesting mechanism--though I don't think the "flash lending" concept has really taken off.

**Comment by osarrouy** [comment]
That’s sound like a great idea for the collateral pool, indeed!

I guess it would make sense to check the before /after equality of `allowance` too, right ?

**Comment by sohkai** [comment]
Ah yes, checking `allowance` would be good too :+1:.
