### ISSUE TITLE
Fix CI coverage check for Agent

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-apps#658]
Both Finance and the Agent app have been added to the allowed failures list in the `.travis.yml` file because they both time out.

Something that both apps share which could be completely unrelated to the root cause of the issue, is that they are the only packages that depend on the `@aragon/apps-vault` and they inherit from it.

**Comment by sohkai** [comment]
Related to https://github.com/sc-forks/solidity-coverage/issues/283.

**Comment by sohkai** [comment]
FWIW it now looks like these are squeaking in at ~45min on Travis, but we should solve the underlying problem anyway.

**Comment by sohkai** [comment]
https://github.com/aragon/aragon-apps/pull/863 Now fixes this for the Finance app, but the Agent app still fails due to some tests not working in coverage.
