### ISSUE TITLE
Voting: show settings

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon-apps#713]
The Voting app has various settings, some of which are changable.

We should show at least the:

- Token the Voting app uses
- Configured support % (can be changed)
- Configured quorum % (can be changed)
- Voting time (cannot be changed)

**Comment by jounih** [comment]
Can the support and quorum be changed per vote?

**Comment by luisivan** [comment]
No, it's an app-wide setting. The idea is that you can deploy a new app with new parameters each time, although I'm not sure if that's what users would prefer vs. per-vote settings

**Comment by sohkai** [comment]
The main awkwardness around per-vote settings is that someone could create votes with ridiculously low settings, encode a finance transfer, and basically 51% attack the org but with only a single token.

Technically you could protect this with ACL params, but it's going to be impossible to recommend this course of action without a proper frontend for those permissions.

**Comment by sohkai** [comment]
Closing for https://github.com/aragon/aragon/issues/1357; we will likely find a generic solution for this instead of per-app settings.
