### ISSUE TITLE
Voting: don't show "execute" steps if no execution script is included in the vote

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon-apps#732]
We could avoid showing the notion of "execution" in the frontend if no execution script is included, to avoid users being confused that a non-binding "yes/no" vote "requires execution"

cc @aragon/design

**Comment by dizzypaty** [comment]
Yes, totally agree. Let's remove the 'Execute vote' button. Also, I think we should change the status to 'Passed' or 'Rejected' rather than 'Executed'.

**Comment by sohkai** [comment]
Closed with #808.
