### ISSUE TITLE
DAO integration tests against Beta templates

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-apps#74]
Construct a dummy DAO with the current apps that will be part of the v0.5 release and interact with it asserting all parts are working as expected. There shouldn't be any surprises but a full test case would be great to have!

~Blocked by #72~

**Comment by izqui** [comment]
This integration tests could be done against templates that will be used in the beta

**Comment by izqui** [comment]
Update: make these integration tests run against the Beta templates https://github.com/aragon/aragon-apps/pull/91

**Comment by bingen** [comment]
Sure!

**Comment by bingen** [comment]
It's done in #112 and #117

**Comment by bingen** [comment]
#117 replaced by #128

**Comment by bingen** [comment]
Closed by #128
