### ISSUE TITLE
Convert ganache-cli.sh to node

### ISSUE THREAD

**Issue by 0x6431346e** [aragon/aragon-apps#755]
File: https://github.com/aragon/aragon-apps/blob/master/shared/test-helpers/ganache-cli.sh

It's being used by the boilerplate now: https://github.com/aragon/aragon-react-boilerplate/pull/46

It "kind of" works on Windows:
```
./node_modules/@aragon/test-helpers/ganache-cli.sh: line 13: nc: command not found
Starting our own testrpc instance at port 8545
npx: installed 54 in 3.046s
listen EADDRINUSE: address already in use 127.0.0.1:8545
./node_modules/@aragon/test-helpers/ganache-cli.sh: line 47: kill: (26724) - No such process
```

**Comment by sohkai** [comment]
Closing; this will be handled in [`contract-helpers`](https://github.com/aragon/contract-helpers) instead.
