### ISSUE TITLE
Payroll: denomination token should be passed as the 'quote' to PPF

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-apps#792]
The denomination token should always be the `quote` and the `base` should be the token that we are asking the price for (see [`PPF.get`](https://github.com/aragon/ppf/blob/master/packages/ppf-contracts/contracts/PPF.sol#L95)). 

This is currently swapped in the Payroll contract so the rates will be inverted.

**Comment by sohkai** [comment]
This is probably something our tests should have caught early on 😅

**Comment by facuspagnuolo** [comment]
Yep, unfortunately, rates are were mocked for a long time
