### ISSUE TITLE
Finance: Date range filter selection shouldn't be applied by default 

### ISSUE THREAD

**Issue by dizzypaty** [aragon/aragon-apps#809]
As a user, I want to be able to select a date range to export my Finance app transfers. 

* Date range should be deselected by default displaying the following hint text: ‘Start date’ and ‘End date’, until user makes a date selection.
* We should indicate today’s date and open the calendar on the current month 
* We should include an Apply and Clear buttons, that removes the current date range selection

**Comment by dizzypaty** [comment]
## Large form factor

<img width="1366" alt="WebApp-1366px - Finance main view" src="https://user-images.githubusercontent.com/7205369/56952372-824efa80-6b3a-11e9-9927-1fa64507a95a.png">

<img width="1366" alt="WebApp-1366px - Finance main view-2" src="https://user-images.githubusercontent.com/7205369/56952402-94c93400-6b3a-11e9-9498-71258dad788a.png">


<img width="1366" alt="WebApp-1366px - Finance main view-1" src="https://user-images.githubusercontent.com/7205369/56952410-9b57ab80-6b3a-11e9-8fa3-10630213566e.png">


<img width="1366" alt="WebApp-1366px - Finance main view-3" src="https://user-images.githubusercontent.com/7205369/56952416-9dba0580-6b3a-11e9-9482-edeede545df9.png">

### Small form factor 
<img width="320" alt="Mobile" src="https://user-images.githubusercontent.com/7205369/56952424-a0b4f600-6b3a-11e9-9ec7-e5caa51e02c1.png">
<img width="320" alt="Mobile-1" src="https://user-images.githubusercontent.com/7205369/56952423-a01c5f80-6b3a-11e9-8d03-efa6153741c9.png">


[Figma files](https://www.figma.com/file/Ffxzu9CDt8KWluyYOVELUnNW/0.7-Usability-testing-issues?node-id=18%3A200)

**Comment by AquiGorka** [comment]
@dizzypaty for mobile/reponsive do we show two sets of `clear`/`apply` buttons?

**Comment by dizzypaty** [comment]
@AquiGorka 

> For mobile/responsive do we show two sets of clear/apply buttons? 

No, only one

> And two titles? with two calendars? Or is it one calendar? 

Just one calendar, full screen 

> If it is one calendar is there a reference to which date (start or end) is the user choosing?

When users tap on the (start/end) date range component, the calendar opens up in a modal, in the current month and displaying today's date. Then, users can select the date range starting by the start date or the end date, as they wish, as it should behave in the same way. 

In the example below, the user selects the 9th of March as the start date and this is reflected on the date range component on top of the calendar. They can scroll down or use the month arrows to select the end date. If they decide to scroll up to go to the previous month, then the start date is refreshed to reflect the new selection. Same behavior for the end date.

![Group 19](https://user-images.githubusercontent.com/7205369/57238086-e2f1a200-7028-11e9-9fc4-10e342923067.png)

Let me know if you need a prototype to help visualize the behavior better! 🛠

**Comment by sohkai** [comment]
Closing for now since the original behaviour was fixed. We will re-implement the dual DatePicker as a separate task.
