### ISSUE TITLE
Payroll: improve radspec descriptions

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon-apps#831]
- Convert salary / second to salary / year
- Fiat tokens
  - Assume tokens have 18 decimals if they're not found
  - Reverse [PPF addressing scheme](https://github.com/aragon/ppf/#tickers-and-token-addresses) to get symbol

**Comment by izqui** [comment]
> Convert salary / second to salary / year

Thinking about whether we should handle leap years or just assume that the yearly salary is `salaryPerSecond * 3600 * 24 * 365`.

> Reverse PPF addressing scheme to get symbol

This can only be done in radspec helpers, how do you feel about handling these special cases there directly?

**Comment by sohkai** [comment]
We might just want to do both as a helper, since we'll need to have a fallback for the salary's token decimals.

**Comment by sohkai** [comment]
Closing; we are deprioritizing Payroll at this moment.
