### ISSUE TITLE
Voting: different percentage calculations

### ISSUE THREAD

**Issue by bingen** [aragon/aragon-apps#838]
The percentage of positive votes was different in the card view and the side panel's quorum (27% vs 26.09%):

Card:

<img src="https://user-images.githubusercontent.com/701095/57388470-87561e80-71b8-11e9-8192-7188e1e9a965.png" height=300>

Panel:

<img src="https://user-images.githubusercontent.com/701095/57388475-8cb36900-71b8-11e9-9842-90758aef54fa.png" height=500>

**Comment by sohkai** [comment]
Closing; we do not have the sidepanel anymore in 0.8.
