### ISSUE TITLE
Rename “Token Manager” as “Tokens”?

### ISSUE THREAD

**Issue by bpierre** [aragon/aragon-apps#839]
The term “Tokens” might still be confusing for users which is something we might want to solve in the future, but I don’t think this change would make it worse in this regard.

I think it makes the menu look cleaner:

<p align=center><img src=https://user-images.githubusercontent.com/36158/57525261-82b17780-732a-11e9-92d3-be8a7fa57c28.png><br>Before

<p align=center><img src=https://user-images.githubusercontent.com/36158/57525262-82b17780-732a-11e9-9837-12fe279f0545.png><br>After

**Comment by luisivan** [comment]
I agree, I think it'd make it cleaner and also conform with our naming scheme (e.g. we don't call Finance the Finances Manager or Voting the Votes Manager). Also the fact that it is the manager/controller of a token is a technicality and shouldn't necessarily be exposed to the user.

I'd like to have @dizzypaty's thoughts on this before executing a rename.

**Comment by dizzypaty** [comment]
I think it's a good idea. We should also rename 'App Center' to 'Apps' for consistency.

**Comment by luisivan** [comment]
I think that makes sense as well. But then I'd re-think the label in the top (*Apps*) since a label and an app would be called the same way @dizzypaty

**Comment by dizzypaty** [comment]
Yeah, that's a good point. IMO I don't think this will be an issue, but perhaps we could use 'Installed apps' for the section header. Will review with all the other copy.

**Comment by luisivan** [comment]
Closing this in favor of https://github.com/aragonone/product/issues/109
