### ISSUE TITLE
Voting: display execution time of a vote

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon-apps#841]
For "enacted" votes, it would be great to show information about when it was enacted (perhaps even showing the transaction hash).

This is useful for tracking when things _actually_ got done through the Voting app (executed can be much much later after an voting ends).

**Comment by sohkai** [comment]
Related to https://github.com/aragon/aragon/issues/697.

**Comment by rperez89** [comment]
Talking with Pierre we found this one : https://github.com/aragon/aragon-apps/pull/962

Is this issue still valid? @sohkai

**Comment by sohkai** [comment]
You are indeed correct! I wasn't sure if I had covered it before, but tested it on Rinkeby and the correct execution time is used!
