### ISSUE TITLE
Finance instance installing issue

### ISSUE THREAD

**Issue by svetlanama** [aragon/aragon-apps#848]
Hi, 

I get this error when I'm trying to install Finance for the token-manager
I'm following this guide [https://forum.aragon.org/t/guide-custom-aragon-organization-deployment-using-the-cli/507](https://forum.aragon.org/t/guide-custom-aragon-organization-deployment-using-the-cli/507)
```
➜  ~ dao install 0x6bBA3d2bfE2714985ED6D459d2C554f3F7e58B9B finance --app-init-args 0x1d51E6A15998aDff22457e9B4a8e5f7DCa06e5C9 2592000 --environment aragon:rinkeby
 ✖ Fetching finance.aragonpm.eth@latest
   → Cannot find artifacts in APM repo. Please make sure the package is published and IPFS or your HTTP server running.
   Checking installed version
   Deploying app instance
 ✖ Cannot find artifacts in APM repo. Please make sure the package is published and IPFS or your HTTP server running.
➜  ~
```

Could you help, please?

**Comment by luisivan** [comment]
This seems related to https://github.com/aragon/aragon-cli, posted a question on the Aragon chat to see if someone can provide help here

**Comment by svetlanama** [comment]
@luisivan Thanks, will follow!

**Comment by sohkai** [comment]
@svetlanama This is a problem with fetching the artifacts (https://github.com/aragon/aragon-cli/issues/377), the guys are working on it :).

**Comment by svetlanama** [comment]
@sohkai  oh, thank you, will wait!

**Comment by 0x6431346e** [comment]
Hey @svetlanama , in the meantime you can try:

- running `aragon ipfs` in a separate terminal

or

- adding the `--apm.ipfs.rpc` flag to the command, e.g.:
```
aragon apm info finance --environment aragon:rinkeby --apm.ipfs.rpc https://ipfs.eth.aragon.network/ipfs 
```

**Comment by svetlanama** [comment]
@danielcaballero  2nd variant helped me, thank you so much!
