### ISSUE TITLE
Token Manager problem

### ISSUE THREAD

**Issue by AlexanderMazaletskiy** [aragon/aragon-apps#859]
Hi, All!
I try
npx create-aragon-app app
npx aragon run --template Template --template-init @ARAGON_ENS

But Token Manager and all actions with token are not working.

When i try to mint tokens
Cannot read property 'length' of undefined
in ActionPathsContent (created by ConfirmTransaction)
in ConfirmTransaction (created by Spring)
in div (created by Context.Consumer)
in StyledComponent (created by SignerPanel__Screen)
in SignerPanel__Screen (created by Spring)
in div (created by AnimatedComponent)
in AnimatedComponent (created by ForwardRef)
in ForwardRef (created by Context.Consumer)
in StyledComponent (created by SignerPanel__ScreenWrapper)
in SignerPanel__ScreenWrapper (created by Spring)
in Spring (created by KeyframesImpl)
in KeyframesImpl (created by ForwardRef)
in ForwardRef (created by Transition)
in Transition (created by SignerPanel)
in div (created by Context.Consumer)
in StyledComponent (created by SignerPanel__Main)
in SignerPanel__Main (created by SignerPanel)
in div (created by Context.Consumer)
in StyledComponent (created by SidePanel__PanelContent)
in SidePanel__PanelContent (created by Spring)
in div (created by Context.Consumer)
in StyledComponent (created by SidePanel__PanelScrollView)
in SidePanel__PanelScrollView (created by Spring)
in aside (created by AnimatedComponent)
in AnimatedComponent (created by ForwardRef)
in ForwardRef (created by Context.Consumer)
in StyledComponent (created by SidePanel__Panel)
in SidePanel__Panel (created by Spring)
in div (created by Context.Consumer)
in StyledComponent (created by SidePanel__Main)
in SidePanel__Main (created by Spring)
in Spring (created by SidePanel)
in SidePanel (created by SignerPanel)
in SignerPanel (created by _default)
in _default (created by Wrapper)
in div (created by Context.Consumer)
in StyledComponent (created by Wrapper__Main)
in Wrapper__Main (created by Wrapper)
in Wrapper (created by Context.Consumer)
in Viewport (created by _default)
in _default (created by App)
in div (created by Context.Consumer)
in StyledComponent (created by styled.div)
in styled.div (created by App)
in PermissionsProvider (created by App)
in ActivityProvider (created by App)
in FavoriteDaosProvider (created by App)
in LocalIdentityModalProvider (created by App)
in ModalProvider (created by App)
in IdentityProvider (created by App)
in App
in ToastHub (created by Main)
in PublicUrlProvider (created by Main)
in ViewportProvider (created by Main)
in div (created by RootProvider)
in RootProvider (created by Main)
in Main
in GlobalErrorHandler
<img width="1440" alt="screen" src="https://user-images.githubusercontent.com/369964/57924830-e3066300-78ae-11e9-9579-cbaafd0d6e65.png">

**Comment by sohkai** [comment]
cc @0xGabi wondering if this is due to the Token Manager being outdated in aragen?

**Comment by 0xGabi** [comment]
I been trying to reproduce this error since yesterday but it's working fine in my pc. I removed my local `snapshot` and `~/.ipfs`. Will keep looking it

**Comment by sohkai** [comment]
@AlexanderMazaletskiy Could you give us which version of aragonCLI you have installed, and perhaps put up the repo you're working off of on Github for analysis?
