### ISSUE TITLE
dao acl create: Cannot read property 'description' of undefined

### ISSUE THREAD

**Issue by svetlanama** [aragon/aragon-apps#882]
Hi,

I'm following this [instruction](https://forum.aragon.org/t/guide-custom-aragon-organization-deployment-using-the-cli/507) 
and noticed that commands related to assigning grants  
like ```dao acl create ....```
give me an error ```Cannot read property 'description' of undefined```

The error behavior is unpredictable (sometimes it requires a delay before calling it, sometimes it does not help)
The thing that I can not achieve the end of instruction the final result (since there are a few commands and one of them every time fails, which makes me start everything from the beginning).

Wonder if there is some way to control this step.
Thanks.

**Comment by luisivan** [comment]
Hey there! This seems like an aragonCLI error. Can you re-create the issue at https://github.com/aragon/aragon-cli/issues/new?labels=bug&template=bug.md? Thanks!

**Comment by svetlanama** [comment]
Done,
https://github.com/aragon/aragon-cli/issues/497

Thanks!
