### ISSUE TITLE
Finance: deposits doesn't detect token amounts correctly

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon-apps#888]
On an account with both ETH and tokens, the tokens selector doesn't detect the account's balances correctly.

It seems like it might be an off by one error on the index; selecting the token after ETH displays the correct ETH balance 🤷‍♂.

--------

ETH balance:
<img width="349" alt="Screen Shot 2019-06-17 at 7 29 06 PM" src="https://user-images.githubusercontent.com/4166642/59624410-f9663f80-9136-11e9-9a77-29f08104b653.png">

ETH selected:
<img width="419" alt="Screen Shot 2019-06-17 at 7 29 12 PM" src="https://user-images.githubusercontent.com/4166642/59624415-fcf9c680-9136-11e9-8a66-a77c7598f080.png">

DAI (next token) selected:
<img width="421" alt="Screen Shot 2019-06-17 at 7 34 39 PM" src="https://user-images.githubusercontent.com/4166642/59624421-fff4b700-9136-11e9-93f6-7b297a8fadcc.png">

Token list (DAI comes after ETH):
<img width="415" alt="Screen Shot 2019-06-17 at 7 34 43 PM" src="https://user-images.githubusercontent.com/4166642/59624424-02571100-9137-11e9-9dd1-7c6025174489.png">

**Comment by AquiGorka** [comment]
@sohkai I tried with different wallets and networks (mainnet and rinkeby) with wallets holding different assets and even when setting a custom token and the balance rendered was correct.
If you could help me reproduce I can further investigate.
Posting a video of a wallet with a mainnet org and correct balances:

https://www.loom.com/share/95c82a9cabc5412593642055c29b64ab

**Comment by luisivan** [comment]
It worked for me too a couple days ago

**Comment by sohkai** [comment]
As it turns out, this was due to my account not being enabled.

However, now I'm wondering what account we were using to fetch those balances from... :shrug:.
