### ISSUE TITLE
Change indentation from 4 to 2 spaces

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-apps#89]

**Comment by bingen** [comment]
What's the point of this? Not a big fan of this kind of changes, but in case of doing it, it would be good to close all opened PRs first.

**Comment by renexdev** [comment]
To standardize the format I imagine... done

**Comment by bingen** [comment]
Ya, well, the format was already ['standard'](http://solidity.readthedocs.io/en/develop/style-guide.html#indentation).
See discussion [here](https://github.com/aragon/aragonOS/issues/221) anyway.

**Comment by renexdev** [comment]
ok, I didn't see it... so let's wait for closing other PRs =)

**Comment by sohkai** [comment]
Closing as we'll be sticking with the solidity convention of 4 spaces.
