### ISSUE TITLE
Token Manager: owner initiated token burn

### ISSUE THREAD

**Issue by lkngtn** [aragon/aragon-apps#919]
There are cases where it would be handy to be able to allow users to burn their own tokens without requiring a vote. Currently the Token Managers `burn()` function allows burning any and all tokens, so it is not practical to grant this to all token holders. 

In order to allow any token holder to burn **only** their own tokens we would need to add new functionality. I think this could be accomplished by adding a new `personalBurn()` function or by putting that logic in a standalone forwarder or ACL oracle. 

I don't have a strong preference on the approach, though I lean towards either the forwarder or oracle as I don't think this is a universally applicable feature of the token manager.

**Comment by sohkai** [comment]
I'm wondering what circumstances a user would want to do this?

As you said, it is certainly easy functionality to add to the Token Manager, but hard to imagine someone invoking this without something else happening in tandem (e.g. a ragequit), which would require at least a forwarder.

**Comment by luisivan** [comment]
Cannot you just send your tokens to `0x000...`? It wouldn't change the token supply count, but it'd be the same from a user perspective

**Comment by lkngtn** [comment]
> I'm wondering what circumstances a user would want to do this?

One situation which came up was within the Coop, Tokens were used as membership in the org there was no way for a member to relinquish their membership token. In order to burn a token we would have had to create a vote and have other member approve the vote, which purely from a practicality perspective is quite inefficient and doesn't make a lot of logical sense. If a user is trying to relinquish their token they should not need approval from the rest of the member in order to do so (this is just a waste of transactions and attention). 

What ended up happening in the Coop is that people simply stopped voting and engaging with the org. Eventually enough of the membership did this which resulted in issues where it was difficult to meet approval quorum, and votes appeared illegitimate because of a lack of participation. 

> Cannot you just send your tokens to 0x000...? It wouldn't change the token supply count, but it'd be the same from a user perspective

Yes this effectively burns the token, but because it does not remove the token from the supply calculations like quorum and participation are impacted. 

For what its worth I would not consider this a high priority issue, but felt it was worth documenting so it can be referenced in the future.

**Comment by sohkai** [comment]
Closing; we can evaluate this in future releases of the Token Manager.
