### ISSUE TITLE
Payroll App: address administration by every address-holder in a distributed manner

### ISSUE THREAD

**Issue by DISC30** [aragon/aragon-apps#957]
It is crucial that the adding and removal of addresses/contributors from projects be done in a distributed manner (otherwise we end up with centralized funds like the rejected [EIP2025 inflation fund](https://www.cryptoglobe.com/latest/2019/08/circle-research-examines-the-debate-around-ethereums-funding-model/) and contentious [Zcash dev fund](https://forum.zcashcommunity.com/t/future-of-zcash-dev-funding-megathread-everything-in-one-place/34063/2)). We wrote up the distributed design on https://github.com/disclosure-exchange/whitepaper/wiki/R&D:

**Step 1**

Any member of the DAO can create a project in the DAO by specifying:

i. the project repository

ii. the wallet address of the project fund (in, say, a readme file)

**Step 2**

Anyone can become a project member (receive funds according to merit) by adding their wallet address to the project (by, say, forking the project and updating the readme).

**Step 3**

Members (funders, workers) of a project (they choose which fork to use) continuously use their DAO tokens to signal % merit (support) for the subprojects. The % of incoming project funds received by a subproject is equal to the current % merit held by the subproject:

subproject's merit ÷ sum of all subprojects' merits = incoming funds to subproject ÷ incoming funds to project

**Step 4**

This is applied recursively to each DAO/project/subproject/…/task/subtask/contributor.

**Comment by sohkai** [comment]
Thanks for the comments @DISC30!

The Payroll app has been designed to be _generic_ as to who can add new members; it has a role set up through aragonOS's permissioning system such that you can declare an account, an app (e.g. voting), etc. to be the holder of the permission to add new employees and set their salaries.

It can go as decentralized as you'd like it to be :).
