### ISSUE TITLE
Finance: failed transfers for some tokens when receiver is 0x00...00

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-apps#997]
Both Finance and Vault allow transferring tokens to the zero address (`0x00..00`) which is sometimes used for burning tokens when the token doesn't support it natively.

Unfortunately, some token implementations (including [OpenZeppelin's](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/ERC20.sol#L155-L156)) revert when sending tokens to `0x00...00`, which makes Finance transfers revert. Other tokens may have other restrictions for transfers (like our org tokens when set to non-transferable).

We should ensure that the token transfer can happen or show the user a warning (or prevent them from creating the transfer). This could be checked by performing an `eth_call` (or estimating gas if we don't want to show the error reason) simulating the token transfer that will eventually occur (`web3.eth.call({ from: vault, to: tokenAddr, data: token.transfer.getData(receiver, value) })`).

The proposed solution above is certainly a patch, and this could be more generally solved at the aragon.js level, trying to prevent votes to be created for impossible actions (and show error messages from revert reasons).

This is particularly bad when there is a vote involved (almost always for transfers), because the client will happily create the vote and users will only know that there is a problem when attempting to execute the vote and get a `The action failed to execute. You may not have the required permissions.`.

**Comment by sohkai** [comment]
Thinking about this, this is mostly likely an issue with aragon.js itself; when we do transaction pathing, we may not actually check that the final step is executable. We do make sure that every forward "above" that final execution is possible though.

**Comment by sohkai** [comment]
Closing this to mark it as a symptom of https://github.com/aragon/aragon/issues/1280.
